aws/amazon-q-developer-cli

- crates/q_cli/src/cli/translate.rs
This fixes the translate prompt for non-macOS operating systems. 
> fix: add operating system to translate prompt

- build-scripts/build.py
- Recalculate the sha for the deb when signing is enabled. This shouldn't cause any issues with updating since this is the first version released for Linux.
> fix: sha calculation for the Linux deb

- Cargo.toml
- deny.toml
- This PR adds an ignore for [RUSTSEC-2017-0008](https://rustsec.org/advisories/RUSTSEC-2017-0008.html) which is currently causing the cargo deny checks to fail.
> chore: add ignore for RUSTSEC-2017-0008

- deny.toml
> chore: add cargo deny ignore for gtk3-rs

- crates/fig_install/src/index.rs
- crates/fig_install/src/lib.rs
- crates/fig_install/src/linux.rs
- Update the file type of update packages for Linux minimal installations to tarZst instead of tarGz. The release for v1.4.6 (included in v1.5.0) has broken update logic for Linux minimal installs where the app will always download a tarGz and attempt to unpack using zstd. This change will revert back to the previous behavior of always using tarZst.
- Add some extra debug statements when updating.
> fix: minimal Linux installation filetype

- build-scripts/test.py
- Skip running desktop fuzz tests since it is blocking the macOS build.
> fix: exclude desktop fuzz tests

- crates/fig_desktop/src/platform/linux/ibus.rs
- crates/fig_desktop/src/platform/linux/integrations.rs
- crates/fig_util/src/terminal.rs
- extensions/gnome-extension/src/extension.ts
- extensions/gnome-legacy-extension/src/extension.js
- Improves terminal detection on Linux by updating the active terminal state whenever we receive notifications from Xorg or the GNOME Shell extension. This is required for Guake support, and should fix some other flaky edge cases as well.
> fix: improve terminal detection on Linux

- crates/macos-utils/accessibility-master/aq/src/main.rs
> fix(macos-utils): remove redundant `fn main` line

- .github/workflows/npm-publish.yml
The first attempt at running the action failed, this update applies some of the config from here: https://docs.npmjs.com/generating-provenance-statements#example-github-actions-workflow
> ci: add registry-url and provenance to npm publish

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/terminal.rs
For the `q chat` command, also allow piping text into the q chat command.
#258 
Similarly to `smartcat`, check if we're piping text, if so, then the chat input will be fetched from the stdin.
> fix: accept text through pipes in chat

- crates/fig_util/src/terminal.rs
This PR adds support for [Ghostty](https://ghostty.org/) resolving #323. The changes will need to be verified in a build before release as the IME is difficult to build locally.
> feat: add support for Ghostty

- README.md
discovered some issues while setting up 
- Fix Rust command: `rustup toolchain default stable` → `rustup default stable`
- Update rtx → mise references (tool was renamed)
- Add missing mise installation steps
> docs: update README for mise installation and rustup command correction

- .github/workflows/rust.yml
- crates/alacritty_terminal/src/ansi.rs
- crates/amzn-toolkit-telemetry/src/config/endpoint.rs
- crates/fig_api_client/src/error.rs
- crates/fig_auth/src/builder_id.rs
- crates/fig_desktop/src/main.rs
- crates/fig_desktop/src/platform/macos.rs
- crates/fig_desktop/src/protocol/icons.rs
- crates/fig_desktop/src/remote_ipc/mod.rs
- crates/fig_desktop/src/utils.rs
- crates/fig_desktop_api/src/init_script.rs
- crates/fig_os_shim/src/env.rs
- crates/fig_util/src/terminal.rs
- crates/figterm/src/main.rs
- crates/q_cli/src/util/mod.rs
- crates/shell-color/src/lib.rs
- crates/zbus/src/abstractions/executor.rs
- crates/zbus/src/address/transport/mod.rs
- crates/zbus/src/guid.rs
- crates/zbus/src/message/field.rs
- crates/zbus/src/proxy/mod.rs
- rust-toolchain.toml
> build: update to rust 1.84.0

- crates/fig_desktop/src/main.rs
This fixes an issues that was accidently introduced in #394. To prevent this again I have marked the functions in the file as `#[must_use]`.
> fix(fig_desktop): exit code not propagated by main

- crates/figterm/src/inline/mod.rs
This resolves #445, currently additional lines are potentially being returned which breaks the inline recommendations. This PR uses a Regex to remove any additional content with the pattern of: `{next_line_number}\s+.*`
> fix: extra lines in inline recommendation

- build-config/buildspec-linux-ubuntu.yml
- `pnpm` is failing to download because the version configured in the package.json includes a `+sha` suffix. Therefore, extracting only the version.
> fix: build config on Ubuntu

- crates/fig_test_utils/src/server.rs
- The `fig_test_utils` crate contains a test that verifies that a local server is stopped once the variable owning the value is dropped. This seems to be flaky since we need to wait some time for the OS to release it, therefore just increasing the timeout.
> fix: Increase sleep time in fig_test_utils server test

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/use_aws.rs
Error case (with no validation):
Happy path:
Tested using the stub of: 
```json
[
[
"Let me use the `use_aws` tool to get your item.",
{
"tool_use_id": "1",
"name": "use_aws",
"args": {
"service_name": "dynamodb",
"operation_name": "get-item",
"parameters": {
"--table-name": "AGI_MEMORY",
"--key": "{\"memory_id\": {\"S\": \"49d649c7-b772-4578-968c-c20240844a4a\"}}"
},
"region": "us-west-2",
"profile_name": "default",
"label": ""
}
}
],
[
"Hope that looks good to you!"
]
]
```
> fix: outputs error when tool execution fails

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- Client now televises tool validation error to users prior to sending associated feedback back to model
> fix: handles tool validation errors

- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- At the time of writing, backend will return ISE if user denies tool use request. 
- This is rectified by deleting the convo history prior to sending a new message. 
- Deletes convo history on tool deny
> fix: deletes history on tool deny

- crates/q_cli/src/cli/chat/mod.rs
> fix: allow user to retry on non-client error

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/execute_bash.rs
- crates/q_cli/src/cli/chat/tools/fs_read.rs
- crates/q_cli/src/cli/chat/tools/fs_write.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/tool_index.json
- crates/q_cli/tests/chat_response_stubs/fs_write_file_unknown.json
- Add timing to tool execution, and some extra display demarcation
- don't add syntax highlighting if the terminal does not support 24bit colors
- make "interactive" a required field in `execute_bash`
> fix: various issues with display and bugs in chat

- crates/q_cli/src/cli/chat/tools/execute_bash.rs
- Making the `interactive` field an option in rust, since I encountered one edge case where it still seemed to fail validation. This shouldn't be required but is added just as an extra precaution.
> fix: Make the execute_bash interactive field an Option

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/tool_index.json
- Adding an env var `Q_CHAT_SKIP_TOOL_CONSENT` to automatically consent to a tool use if set.
- Updating the aws spec to prefer `s3api` over `s3`, since the model seems to generate operations using the `s3api` format and yet still use the `s3` command.
> feat: add env var to skip tool use consent, other minor changes

- crates/q_cli/src/cli/chat/mod.rs
- Allows users to ctrl-c to exit out a long running tool use without also exiting chat
> feat: Add interrupt for tools

- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
- crates/q_cli/src/cli/chat/tools/fs_read.rs
- crates/q_cli/src/cli/chat/tools/fs_write.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/use_aws.rs
- Adding the `/clear` command to clear conversation history. This is useful in the case where the state gets in a bad state where only InternalServerExceptions are created. This is done by looping in the main `prompt_and_send_request` function which caused a larger diff than usual.
- Add tilde expansion for path handling in `fs_read` and `fs_write`
- Fix a bug with `use_aws` where parameters are sometimes returned capitalized by the model. In this case, we always lowercase parameters.
- Don't prompt for consent on readonly commands. This is currently for all `fs_read` and `use_aws` tools.
- Other minor fixes.
> feat: add /clear command, fix use_aws parameters bug, add tilde expansion, minor fixes

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/parser.rs
- Fix the parser to not buffer assistant text until the end.
> fix: response stream parser buffering assistant text until the end

- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/tool_index.json
- crates/q_cli/src/cli/chat/tools/use_aws.rs
- Allowing mutative actions with `use_aws` tool uses. We require consent for any write actions, and otherwise immediately run read-only actions.
> feat: allow mutative actions with use_aws

- crates/q_cli/src/cli/chat/conversation_state.rs
We need to ensure the history sent to the model always starts with user input. Therefore when truncating history, we need to do it in pairs. 
> pops 2 messages at a time when truncating history

- crates/q_cli/src/cli/chat/tools/tool_index.json
Update the fs_read tool description so that it is used more often. Currently, the model prefers to use the bash tool for listing files in a directory, which requires customer consent.
> Fix: Update fs_read tool so that it is used more often

- crates/q_cli/src/cli/chat/mod.rs
> fix: assigns user input id to distinguish retry tool use event

- rust-toolchain.toml
- typos.toml
> fix: use rust 1.85

- build-config/buildspec-linux-minimal.yml
- build-config/buildspec-linux-ubuntu.yml
- rustup no longer installs implicit tool chains, hence we need to do it manually now. Taking it from the `rust-toolchain.toml` file.
> fix: codepipeline failures when running cargo

- rust-toolchain.toml
- macOS build is failing since going to 1.85, reverting to unblock builds.
> fix: revert back to rust 1.84

- build-config/buildspec-linux-minimal.yml
- build-config/buildspec-linux-ubuntu.yml
- crates/q_cli/src/cli/chat/tools/mod.rs
- rust-toolchain.toml
- typos.toml
- Fix an infinite loop when formatting paths from absolute to relative.
> fix: infinite loop when formatting paths

- build-config/buildspec-linux-minimal.yml
- build-config/buildspec-linux-ubuntu.yml
- crates/fig_api_client/src/clients/streaming_client.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- packages/dashboard-app/src/pages/terminal/chat.tsx
- typos.toml
- Updating the history truncation logic to never surpass the max limit.
- Fix bug with invariants around the history - user message will always be first now.
- Add "tool use interrupted" as a tool result option in the event that the user ctrl+c's during tool execution.
> fix: correct history truncation, tool interruption on ctrl c

- crates/q_cli/src/cli/chat/tools/execute_bash.rs
- Ignore execute bash test since it is failing on musl for some reason. We'll need to fix it at a later date, this is just done to unblock the pipeline.
> fix: ignore failing test on musl

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/parser.rs
- Handling errors when trying to receive the next event in the response stream. If we encounter an error after 59 seconds have passed, then we consider this a timeout and send back a message to the model telling it to break up its response into smaller chunks.
- We are seeing timeouts happen at 100 seconds but I set the timeout to 59 seconds just to be safe, since we had encountered 60 second timeouts previously as well.
> fix: stream timeout handling

- Cargo.lock
- Cargo.toml
- crates/q_cli/Cargo.toml
- crates/q_cli/src/cli/chat/tools/fs_read.rs
- crates/q_cli/src/cli/chat/tools/fs_write.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- try to accommodate hallucinations with `fs_write`
- don't print file content on `fs_read`
> fix: update fs_write tool to try to accomodate hallucinations, other UX changes for fs_read

- deny.toml
- Adding NCSA as an allowed license, since it is approved for use by Amazon
> chore: add allowed license ncsa to deny.toml

- packages/dashboard-app/src/pages/settings/integrations.tsx
While I was setting up my terminal with the amazon-q, I didn't realize it supports Ghostty so added Ghostty wording specifically. https://github.com/aws/amazon-q-developer-cli/pull/335
> chore: add ghostty terminal support wording

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/fs_write.rs
Fixes #768
This commit adds functionality to ensure all files created or modified by the fs_write tool end with a newline character, following Unix text file conventions. The change:
- Adds newline handling to create, str_replace, and insert operations
- Updates test cases to verify the new behavior
- Maintains backward compatibility with existing functionality
- Avoids common Checkstyle and Lint failures due to missing new line or trailing whitespace at the end of a line.
This improves compatibility with other tools and follows standard text file best practices.
#768
This PR addresses issue #768 by ensuring that all files created or modified by the fs_write tool end with a newline character, following Unix text file conventions.
* Added …
> fix (q chat): ensure generated files end with newline character, and no trailing whitespaces

- Cargo.lock
- crates/q_cli/Cargo.toml
- crates/q_cli/src/cli/chat/tools/fs_write.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- Adding a file diff visualization for `fs_write` that displays line numbers. This implementation needs to be improved for truecolor support - currently, we don't highlight the entire document which can result in lines being highlighted incorrectly, consequently impacting the diff.
- Removing the `clean_file_content` function since it was resulting in a lot of errors with the model trying to use str_replace. Essentially, we were writing different content than the model was generating, which thus required it to constantly reread the file to see what we actually wrote.
- Moving the logic for appending a newline to a separate function shared by all `fs_write` commands.
- Fixed bug with append not including a newline at the end of the file.
By submitting this pull …
> feat: improve file diff for fs write

- crates/q_cli/src/cli/chat/mod.rs
- Replicate the behavior of the `node` repl by requiring two consecutive sigint's in order to exit. This is intended to prevent accidental exits when the user spams Ctrl+C.
> feat: dont exit on first ctrl c when at the prompt

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to `1.7.1`
- Adding a `feed.json` entry
> chore: bump version to 1.7.1

- crates/fig_api_client/src/clients/streaming_client.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/parser.rs
- We currently do not show the request id for non-InternalServiceError errors. This change will always show the request id for errors encountered during the response stream, even if the client is the one responsible. This is intended to help debug issues with the backend producing a bad response that *looks* like a client error, but is in actuality a backend error.
> fix: show request id on errors encountered during the response stream

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/fs_read.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/tool_index.json
- Adding a search mode for `fs_read` that searches file lines by a lowercase substring.
- Refactoring `fs_read` into distinct modes: reading files, directories, and searching for files.
- Updating `queue_description` to be `async` - in reality, this should be updated to something more representative of what is being performed (e.g. `prepare` or something). For instance, to give any decent description (diff) for `fs_write`, it is required to perform the diff and write in memory, thus you essentially have to perform the same operation twice.
For a human-readable version of the tool description being set for `fs_read`:
> Tool for reading files (for example, `cat -n`) and directories (for example, `ls -la`). The behavior of this tool is determined by the `mode` …
> feat: add search to fs_read, refactoring fs_read into different modes

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/mod.rs
- Adding a "beta" notice in the `/profile` and `/context` help text to signify that they are subject to change.
> chore: add beta notice to /profile and /context help text

- README.md
*Problem*: 
1. `husky install is deprecated`
2. Shell commands cannot be copied into CLI directly because of the comments added in code-snippets
In husky v9 ([Link](https://github.com/typicode/husky/releases/tag/v9.0.1)), the installation process changed. Instead of using husky install, the recommended approach is now to use the husky command directly, which is already correctly configured in the package.json:
```json
"scripts": {
"prepare": "husky",
"precommit": "lint-staged --config .lintstagedrc.mjs"
}
```
The prepare script with just husky is the correct modern way to set up husky in v9. This automatically runs when you do pnpm install and sets up the git hooks.
The pre-commit hook is also properly configured to run:
```
pnpm run …
```
> Update README file to update commands and make it easy to copy-paste CLI commands directly

- crates/q_cli/src/cli/chat/tools/execute_bash.rs
This PR enhances the `execute_bash` function to support safe piped commands without requiring user confirmation. Previously, piped commands were supported but always triggered a confirmation prompt, which interrupted the user experience. This change allows common read-only piped commands like `find | grep` or `ls | grep` to execute directly when all commands in the pipe chain are validated as safe.
- Modified the command validation logic to check each command in a pipe chain
- Added support for automatically approving piped commands when all components are in the READONLY_COMMANDS list
- Maintained the security prompt for any piped commands containing potentially unsafe operations
- Improved user experience by reducing unnecessary confirmation prompts
- Verified safe piped commands like …
> feat(cli) Bash pipe command safety

- crates/q_cli/src/cli/chat/prompt.rs
1. File/Folder name auto-complete does not currently work in the q-chat window
Extended the `ChatCompleter` to suggest file/folder name auto-completions as fallback
Tested by running - 
`cargo run --bin q_cli -- chat `
See screenshot below for info on what the output looks like -
> Add file/folder name auto-completion in q chat

- build-scripts/build.py
https://github.com/aws/amazon-q-developer-cli/issues/937
Replace hardcoded amd64 reference with dynamic architecture detection based on the target triple. This allows proper AppImage bundle naming for both amd64 and aarch64 architectures.
> fix(build): Support aarch64 architecture in AppImage bundle name (#937)

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/mod.rs
Related: https://github.com/aws/amazon-q-developer-cli/issues/808
- Prints to STDOUT instead.
- Does not print non-response text, e.g. user input prompt, welcome message.
- Runs tools as long as --accept-all is also provided. Otherwise it will error. You can bypass this by asking to not run tools in the prompt.
- Continues to work with pipes, e.g.
- echo "give a cool tip" | q chat --no-interactive -> outputs a cool tip
- echo "give a cool tip" | q chat --no-interactive "write hello world." -> outputs hello world code and a cool tip
- q chat --no-interactive -> does nothing and immediately returns
Does NOT print without any formatting/styling codes or labels. That will require a larger refactor in a separate PR.
By submitting this pull request, I confirm that you can use, modify, copy, and …
> feat(chat): no-interactive mode

- crates/q_cli/src/cli/chat/command.rs
*Issue #, if available:* https://github.com/aws/amazon-q-developer-cli/issues/894
Fixes an issue where pasting error messages or file paths that start with a slash (/) would be incorrectly interpreted as commands. This change improves the command parser to better distinguish between actual commands and text that happens to start with a slash character.
> fix(chat): Improve command parsing to handle paths starting with slash

- crates/q_cli/src/cli/chat/command.rs
There are times when I accidentally type `exit`, `quit`, etc. and know that I did not want to call the LLM.
Adding handling for these cases to avoid unnecessary LLM calls
Improve user experience by detecting when users type common commands like exit, quit, or help without the leading slash prefix. Instead of making unnecessary LLM calls, provide helpful suggestions to use the proper command format (e.g., '/quit', '/help').
> refactor(chat): Add command suggestions for common single-word inputs

- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/tool_index.json
- crates/q_cli/src/cli/issue.rs
**To be squashed**
https://github.com/aws/amazon-q-developer-cli/issues/873
Add the `gh_issue` tool that allows Q to open pre-filled issue templates with additional information. Similar to `q issue`, when asked to report an issue, a browser will open to the template (or URL if the browser cannot be opened).
Features:
- Triggers when asked to create or report an issue, or to open a feature request.
- Adds additional chat information automatically.
- Q could fill in expected/actual behavior, steps to reproduce, title.
- Includes any request IDs that resulted in an error.
- Includes chat context (from `/context show --expand`). This also includes their sizes.
- Includes the last **5** user-assistant requests from the chat transcript. This …
> feat(tools): add gh_issue

- crates/q_cli/src/cli/chat/mod.rs
Currently, running `/context show` doesn't tell users if there are/aren't any files being tracked in the context.
This can be confusing as we show the path-rules, but not the expanded paths by default.
improve context file display by doing the following - 
- Always show context file count regardless of expand flag
- Let users know when no files are currently being added to context
> feat(cli): improve context file display

- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- Take last 10 chats instead of last 5
- Also accept any user input, like commands (/acceptall, /clear).
https://github.com/aws/amazon-q-developer-cli/issues/981
> feat(tools): increase transcript length, record all user input

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- Add the ability to add context to `Tool`s, without passing in awkward args to the generic invoke function.
- Graceful tool error if context fails to be set (should be impossible).
Follow up to: https://github.com/aws/amazon-q-developer-cli/pull/974#discussion_r2017302788
> refactor(tools): add context to report_issue tool

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
This command simply prompts amazon Q to use the `report_issue` tool. Any additional text beyond /issue will be provided in the prompt.
https://github.com/aws/amazon-q-developer-cli/issues/972
> feat(commands): add /issue command to chat

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- record if `accept_all` or `interactive` is true/false
- display list of all available profiles
Related: https://github.com/aws/amazon-q-developer-cli/issues/873
> feat(tools): display chat settings in report_issue

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/parse.rs
*Issue #, if available:* #889 
Modify URL parser to properly handle square brackets in text by saving the input position and resetting it when the complete URL pattern does not match. This ensures square brackets are correctly displayed in chat output when they are not part of a markdown link.
> fix(chat): Fix display of square brackets in chat output

- crates/q_cli/src/cli/chat/input_source.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
Add the MultiLineValidator implementation in prompt.rs to support multi-line editing in the q chat terminal
https://github.com/user-attachments/assets/14d20fad-a668-4b4e-b572-cf3f640c062a
https://github.com/user-attachments/assets/9398ab84-3da6-498a-afc3-7c7845125439
> refactor(chat): Update prompt validator for multi-line input

- crates/q_cli/src/cli/chat/input_source.rs
https://github.com/aws/amazon-q-developer-cli/pull/1044#discussion_r2025311601
Add lines to history to allow navigation using up/down arrow keys
> Fix history-support with multi-line

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
- Empty Line was considered as incomplete prompt instead of re-prompting the user
- Add keyboard symbols (⌥, ⏎) to make shortcuts more recognizable
- Handle empty line inputs by reprompting the user instead of processing
> fix(cli): Improve chat input handling and keyboard shortcut display

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/mod.rs
Implements https://github.com/aws/amazon-q-developer-cli/pull/921 which describes trusting and untrusting specific tools for the current session.
- Start with default permissions. Users can change them from command line or within chat via /tools
- `/acceptall` and `--accept-all` were deprecated in favor of `--trust-all-tools` and `/tools trustall`. They will continue to work, but display a notice and activation functionality of the new commands.
- Command::AcceptAll no longer exists
- UI has been reword a little, see screenshots.
- `report_issue` will include trust override settings in the report.
- Chat supports multiple tool use requests from Q at once. I have refactored the tool flow to allow asking permissions for individual tool requests at a time
- Now, ExecuteTools (checks for …
> feat(commands): granular permissions with /tools

- crates/q_cli/src/cli/chat/mod.rs
Align with other help text.
Before:
After:
> fix(chat): remove unneeded . characters from welcome message

- crates/q_cli/src/cli/chat/mod.rs
#1091 
* Removed the unwrapping of tool_use_clone and passed that directly to `Interrupted`
> fix(chat): cli crashes when tool_uses is none

- crates/q_cli/src/cli/chat/mod.rs
- Updating the help messaging for entering newlines to prioritize `ctrl+j` since it seems to be more commonly supported - for instance, my default keybindings already have something set for Alt+Enter across different terminals.
> refactor(chat): update chat newline messaging to prioritize ctrl+j

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
* Removed `--expand` flag
* Show what `--expand` used to show in `/context show`
> refactor(context): Simplify 'show' command by removing --expand option

- crates/q_cli/src/cli/chat/command.rs
> fix(chat ux): Default `/context` to `/context help`

- crates/fig_integrations/src/ssh/mod.rs
- Removing the `=` sign in the ssh Match condition since a recent update to OpenSSH 9.9 seems to have broken this. See the related issue #1026 
- Users with the broken config will have it corrected upon installing the ssh integration again.
> fix: update ssh integration config to remove '=' in exec condition

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to `1.7.3`
> chore: bump version to 1.7.3

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
Issue: https://github.com/aws/amazon-q-developer-cli/issues/1042
Attaches a red ! to ">" prompt indicator if **all** available tools are trusted.
> feat(chat): all-tools-trusted indicator

- crates/q_cli/src/cli/chat/mod.rs
https://github.com/aws/amazon-q-developer-cli/issues/1080
- Test /tools usage on how tools are executed
- Test running multiple tools at in one Q response
> test(tools): add integration tests for /tools + chat usage

- crates/q_cli/src/cli/chat/chat_state.rs
- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- Add functionality to summarize and clear conversation history
- Allow presenting the summary with --summary flag
- Let /compact take an optional prompt to modify summary request
- Ensure the model acknowledges the summary in future responses
- Modify clear() method to optionally preserve summary
- Warn users about context limit based on number of characters
[see issue : 1067](https://github.com/aws/amazon-q-developer-cli/issues/1067)
> feat: Introduce /compact command

- feed.json
- Adding back the `/compact` command to feed.json, and updating the date to tomorrow.
> chore: add compact command to feed

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- Updating the `/tools` permission display to be more consistent. Currently, stating "readonly commands" is a bit confusing and inconsistent with "per-request" messaging. Now, we will display when to ask for permission, outside of the "Trusted" messaging.
Some example screenshots:
> refactor(chat): update the /tools permission copy to be more consistent

- Cargo.lock
- crates/fig_api_client/src/clients/client.rs
- crates/fig_api_client/src/clients/streaming_client.rs
- crates/fig_auth/src/builder_id.rs
- crates/fig_aws_common/Cargo.toml
- crates/fig_aws_common/src/http_client.rs
- crates/fig_aws_common/src/lib.rs
- crates/fig_telemetry/src/lib.rs
- Due to [an open issue in the rust aws sdk](https://github.com/awslabs/aws-sdk-rust/issues/169), we cannot use the system proxy (ie, `HTTP_PROXY` / `HTTPS_PROXY` env var) when making requests. This is causing issues for users in corporate networks that require all outbound traffic to go through a proxy server. The only solution is to use a client-owned http client [as noted in this comment](https://github.com/awslabs/aws-sdk-rust/issues/169#issuecomment-2729530913).
- Creating an `aws-smithy-runtime-api::client::http::HttpClient` implementation using the same `reqwest` client created globally in the `fig_request` crate. `reqwest` supports use of the system proxy by default, thus this seemed to be the simplest path forward for now.
Since this will be used for all …
> fix: set a reqwest client as the http client for the aws sdk clients to enable system proxy use

- README.md
Change 'Window' to 'Windows' in the WSL installation instructions for better clarity.
🤖 Assisted by [Amazon Q Developer](https://aws.amazon.com/q/developer)
> docs: Fix typo in Windows installation section

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/mod.rs
https://github.com/aws/amazon-q-developer-cli/issues/1202
Before:
After:
> fix(cli): remove --accept-all references from chat help

- crates/q_cli/src/cli/chat/context.rs
- crates/q_cli/src/cli/chat/hooks.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/execute_bash.rs
RFC: https://github.com/aws/amazon-q-developer-cli/pull/1050
This PR begins implements the required logic for executing hooks. This PR has pending follow ups to handle the remaining items. Note that the logic is currently inaccessible from a normal chat session.
It implements:
- "Hooks", which are defined in the context json files. They are loaded along with the normal context.
- "conversation_start" hooks that run once and are attached to the top of the context,
- "per_prompt" hooks that run each time there is a prompt, and are attached to the user prompt.
- Start with 1 hook type, "inline hooks", which simple execute a bash command.
- A HookExecutor to asynchronously call hooks in order from the configs.
- Logic to add/remove/enable/disable hooks via commands
- A cache to hold recent …
> feat(context): load and execute context hooks

- crates/q_cli/src/cli/chat/mod.rs
- package.json
Sometimes users may habitually type `/clear` to clean the console output but in `q chat`, this actually erase chat history. 
Adding a confirmation dialog to prevent mistakes.
https://github.com/user-attachments/assets/76a17b79-9700-4e3d-b295-228d3378d8b5
> Ask for confirmation before clearing chat history

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
*Issue #, if available:* https://github.com/aws/amazon-q-developer-cli/issues/1086
*Description of changes:* 
1. Added a new `ResetSingle` variant to the `ToolsSubcommand` enum in `crates/q_cli/src/cli/chat/command.rs`
2. Updated the `AVAILABLE_COMMANDS` constant to include documentation for the new reset single tool command
Added handling in the command parser to support both `/tools reset (reset all)` and `/tools reset <tool_name>` (reset single)
Added a new `reset_tool` method to the `ToolPermissions` struct in `crates/q_cli/src/cli/chat/tools/mod.rs`
5. Added command handling for the `ResetSingle` variant in the Chat state machine in `crates/q_cli/src/cli/chat/mod.rs`
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> feat: enhance tools reset

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
Follow up to: https://github.com/aws/amazon-q-developer-cli/pull/1176
RFC: https://github.com/aws/amazon-q-developer-cli/pull/1050
- Add new command `/context hooks`
- subcommands to add/remove and enable/disable hooks
- Context hooks are called then added to the beginning of the chat history as context, or to each prompt, depending on what is chosen.
> feat(context): context hooks with `/context hooks`

- crates/q_cli/src/cli/chat/command.rs
Handle slash commands properly to avoid mistakes.
Produces
Error: Unknown command: '/a'. Type '/help' to see available commands.
To use a literal slash at the beginning of your message, escape it with a backslash (e.g., '\//hey' for '/hey').
> fix: handle slash commands

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/context.rs
- crates/q_cli/src/cli/chat/hooks.rs
- crates/q_cli/src/cli/chat/mod.rs
Follow up to https://github.com/aws/amazon-q-developer-cli/pull/1176#discussion_r2040038176
- Seamlessly de-duplicate hook names in a single config instead of making the user deal with it
- Also checks the config file and deduplicates any names in case they were added outside of chat
- Use separate hook caches for profile vs global hooks:
- Allows hooks to have the same names across profile/global configs
- Allows us to clear execute cache easily when switching profiles
> feat(context): de-duplicate hook names within configs

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/prompt.rs
- crates/q_cli/src/cli/chat/summarization_state.rs
- crates/q_cli/src/util/token_counter.rs
https://github.com/user-attachments/assets/8c7c32ef-4d11-4c0f-90e1-13d5a9d2bc76
Currently, I'm basically reconstructing the `FigConverationState` output and that's gonna be hard to scale and maintain. It's a beta feature with rough est. Will follow up with a more accurate representation once #1175 is resolved.
Follow on ticket: #1178
> feat: /usage

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/execute_bash.rs
- crates/q_cli/src/cli/chat/tools/fs_read.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- crates/q_cli/src/cli/chat/tools/mod.rs
- crates/q_cli/src/cli/chat/tools/use_aws.rs
- crates/q_cli/src/cli/issue.rs
See #998 for motivation
V1: 
https://github.com/user-attachments/assets/aa74b222-ed1d-4e22-809f-98c190efe41e
[Update] V2:
> Improve agentic execution UI

- crates/q_cli/src/cli/chat/input_source.rs
- crates/q_cli/src/cli/chat/mod.rs
*Description of changes:* This makes it so users can configure which key is used with ctrl to enter the skim thing
> chore: make skimCommandKey configurable and add help text

- .github/workflows/check-merge-conflicts.yml
For long-running feature branches, it is possible that the beta or feature branch starts deviating from main, which can cause large merge-conflicts at a later time.
This workflow automatically checks if PRs would create merge conflicts with the main branch. It performs the following actions:
1. Skips checks if the PR is targeting the main branch
2. For PRs to other branches, attempts a test merge with main
3. Fails the workflow if conflicts are detected, prompting users to rebase
4. Provides clear error messages with instructions for resolving conflicts
5. Handles Git identity configuration and merge state properly
The workflow helps maintain a clean branch structure by encouraging developers to resolve conflicts before creating PRs.
By …
> ci: add workflow to check for merge conflicts with main branch

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/mod.rs
- Don't store per-prompt context in every user message in the conversation history. We will just attach it to the latest user message without storing it.
- We can save tokens this way, and it doesn't seem useful at this time for Q to reference back to previous (irrelevant) per-prompt hooks.
- Improve the system prompt so that Q is more likely to use/follow context from hooks. Previously Q was a little a stubborn about it.
> feat(context): don't store per-prompt hooks, improve system prompt for hooks

- crates/q_cli/src/cli/chat/context.rs
- crates/q_cli/src/cli/chat/hooks.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/execute_bash.rs
Update the UI of running hooks to align with the loading UI of MCP.
https://github.com/user-attachments/assets/f34700d7-0488-457d-b6ff-0aff5a58f693
> feat(context): improve hooks execution UI

- crates/q_cli/src/cli/chat/command.rs
- crates/q_cli/src/cli/chat/mod.rs
https://github.com/aws/amazon-q-developer-cli/issues/1157
- Make trustall/acceptall warning more verbose.
- Trustall/acceptall warning will show if you start chat with -a or --acceptall or --trust-all-tools
- /trust and /untrust takes an unlimited amount of tools at a time
- /trust and /untrust will display an error if you specify a tool name that does not exist
> feat(/tools): update trustall UX, /trust and /untrust capability

- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/message.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/token_counter.rs
Addressing some followups to #1275 
- only run context hooks on new user prompts
- don't include per prompt context in the conversation history
- remove comments, minor cleanup
> refactor(chat): address auto compaction regressions and minor cleanup

- Cargo.lock
- Cargo.toml
- feed.json
- Bumping the version to `1.8.0` and adding entries to `feed.json`
> chore: bump version to 1.8.0

- crates/q_cli/src/cli/chat/message.rs
- Making sure the next message does not contain only whitespace, since that seems to cause ISE's
> fix: remove whitespace from user input message to prevent ISEs

- crates/q_cli/src/cli/chat/context.rs
- crates/q_cli/src/cli/chat/conversation_state.rs
- crates/q_cli/src/cli/chat/input_source.rs
- crates/q_cli/src/cli/chat/message.rs
- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/tools/gh_issue.rs
- crates/q_cli/src/cli/chat/util/mod.rs
- crates/q_cli/src/util/spinner.rs
Doing some minor prep to make moving all of the chat code to a separate crate a bit easier.
- Updating the `q chat` imports to be relative
- Copy/pasting the current region check code, since it's only otherwise used in `translate`
- Moving the terminal notification code to a util mod in chat
> chore: update chat imports to be relative, minor code refactoring

- crates/q_cli/src/cli/chat/mod.rs
- crates/q_cli/src/cli/chat/parser.rs
- Updating the tool use stream timeout to handle cases where we do receive a stop event, but still fail serialization after waiting for a long time
> fix: add check for tool use timeouts

- crates/q_cli/src/cli/chat/mod.rs
- Adding the request id to the error message presented to the user in the case invalid JSON is returned by the model.
> fix: add request id to errored json message

- crates/q_chat/src/command.rs
- crates/q_chat/src/lib.rs
- crates/q_chat/src/prompt.rs
> refactor(/compact): deprecate --summary to show summary by default

- crates/q_chat/src/conversation_state.rs
- crates/q_chat/src/message.rs
- Updating the `---` divider blocks used for formatting the context and user message portions to match the same wording as is currently being updated in the system prompt.
> fix: update context and user content dividers to match system prompt content

- crates/q_cli/src/cli/installation.rs
- crates/q_cli/src/cli/user.rs
- Adding a flag to always use device code flow for `q login`. This is useful in cases where we think we can open a browser successfully, but are actually unable to handle redirects required for PKCE.
- Fixing sigint handling to actually respect ctrl+c
> fix: add flag for logging in with device flow on CLI, fix broken sigint handling during auth

- Cargo.lock
- Cargo.toml
- crates/q_chat/src/lib.rs
- feed.json
This is for an emergent deployment. 
This will likely have a follow up fix. 
> fix: shortens tip message to avoid overflow subtraction

- crates/q_chat/src/lib.rs
Sets the custom tool flag to true for custom tools. 
This is done to correctly reflect the number of custom tool invocation in the telemetry.
> fix: sets custom tool flag for custom tools

- packages/dashboard-app/src/components/installs/modal/login/index.tsx
- Fixes the issue with the profile modal not closing after selecting a profile
> fix: modal not closing during login after selecting a profile

- crates/q_chat/src/lib.rs
Fixed a bug where the /context command description appeared twice in the help text
displayed by the /help command.
> fix(chat): Remove duplicate /context command help text

- crates/q_cli/src/cli/user.rs
- packages/dashboard-app/src/components/ui/select.tsx
- packages/dashboard-app/src/pages/settings/preferences.tsx
- Updated the `SelectItem` component to accept an optional `description` prop.
- In the profile dropdown, passed `profile.arn` as the description
This helps users distinguish between profiles with the same name but different ARNs, especially in multi-account or multi-region setups.
> fix: add profile arn in user profile subcommand and dashboard

- crates/q_chat/src/lib.rs
#1373 
Fixed an issue where the guide text (shortcuts and separator line) was being output in no-interactive mode. 
Modified the code in crates/q_chat/src/lib.rs to wrap the UI guide text display code with `self.interactive`, ensuring that guide text is only displayed in interactive mode.
This change fixes the issue, however, I think we should create a follow-up task to review and refactor interactive mode handling more comprehensively.
> fix(chat): Prevent guide text output in no-interactive mode

- .github/workflows/rust.yml
- crates/q_cli/tests/cli_user.rs
- Replacing the code coverage step in github actions with cargo test since cargo-llvm is giving an error in a crate generated with bindgen, and there's currently no straight path forward for skipping this error.
- Example of a failed run: https://github.com/aws/amazon-q-developer-cli/actions/runs/14758904237/job/41434325142
> fix: replace code coverage step in github actions with cargo test

- crates/q_chat/src/lib.rs
> fix: clean up formatting before prompting for input

- docs/installation/linux.md
This PR enhances the Linux installation documentation by:
- Adding desktop environment integration instructions for AppImage users
- Providing a complete example for creating desktop shortcuts
- Improving the overall user experience for Linux installations
These changes help Linux users better integrate Amazon Q into their workflow and desktop environments.
I acknowledge that by submitting this pull request, I am contributing code to an AWS open source project and agree to the terms of the project's licensing.
🤖 Assisted by [Amazon Q Developer](https://aws.amazon.com/q/developer)
> docs: Improve Linux installation documentation

- crates/q_chat/src/lib.rs
- crates/q_chat/src/shared_writer.rs
This is a follow up fix for the overflow subtraction encountered when tip in tip boxes contain single words that are longer than the box width (e.g. a link) on the release of 1.9.0.
- `draw_tip_box` now accounts for single words that are longer than the inner width of the tip box.
Long single words are now also wrapped:
Normal tips are displayed as usual:
> fixes draw_tip_box

- crates/q_chat/src/lib.rs
> fix: unable to hide popular shortcuts when greeting screen is turned off

- Cargo.lock
- Cargo.toml
- crates/fig_desktop/src/install.rs
- crates/fig_desktop/src/main.rs
- crates/fig_diagnostic/src/lib.rs
- crates/q_cli/src/cli/doctor/checks/linux.rs
- crates/q_cli/src/cli/internal/mod.rs
- crates/q_cli/src/util/desktop.rs
- crates/q_cli/src/util/mod.rs
- Bumping sysinfo to `0.33.1`
- `new` is equivalent to `nothing`
0.32.0 - https://docs.rs/sysinfo/0.32.0/src/sysinfo/common/system.rs.html#2238-2240
0.33.1 - https://docs.rs/sysinfo/0.33.1/src/sysinfo/common/system.rs.html#2086-2088
> chore: bump sysinfo to 0.33.1

- crates/q_chat/src/lib.rs
Add a new tip to the rotating tips array that informs users about enabling terminal notifications with the settings command.
🤖 Assisted by [Amazon Q Developer](https://aws.amazon.com/q/developer)
> Add terminal notification tip to rotating tips

- crates/q_chat/src/lib.rs
- crates/q_chat/src/tool_manager.rs
- crates/q_chat/src/tools/mod.rs
- crates/q_chat/src/tools/think.rs
- crates/q_chat/src/tools/tool_index.json
- crates/q_cli/src/cli/settings.rs
`With tool enabled` - `q settings chat.enableThinking true`
`with tool disabled` - `q settings chat.enableThinking false`
```
Trusted tools can be run without confirmation
* Default settings
> use think tool
I don't have a "think tool" available in my current toolset. The tools I can use include:
• fs_write: For creating and editing files
• use_aws: For making AWS CLI API calls
• execute_bash: For executing bash commands
• fs_read: For reading files and directories
• report_issue: For reporting issues with the chat
Is there something specific you'd like me to help you with using these available tools? I can help with file operations, AWS CLI commands, bash execution, or other tasks related to the Amazon Q CLI project you're working on. …
```
> feat(tools): Add think tool with option to disable it.

- Cargo.lock
- crates/q_chat/Cargo.toml
- crates/q_chat/src/conversation_state.rs
Add current UTC time in <currentTimeUTC> XML tags at the end of user prompts. This allows the model to have access to the current time when needed for date/time related queries.
This lets us enable prompt caching in the backend.
> feat(chat): Add current UTC time to user messages

- crates/fig_os_shim/Cargo.toml
- crates/fig_os_shim/src/fs.rs
- crates/fig_os_shim/src/platform.rs
- crates/fig_os_shim/src/process_info/mod.rs
- crates/fig_os_shim/src/process_info/pid.rs
- crates/fig_os_shim/src/process_info/windows.rs
This PR adds Windows support to the OS shim layer, enabling the Amazon Q Developer CLI to run natively on Windows platforms. This is a significant enhancement to our cross-platform compatibility and addresses user requests from the Windows 
discussion thread.
• Implemented Windows-specific OS operations in the OS shim layer
• Added conditional compilation for Windows-specific code paths
• Ensured file path handling works correctly on Windows systems
• Maintained compatibility with existing Linux and macOS implementations
• Verified functionality on Windows 11
• Confirmed that existing Linux and macOS functionality remains intact
• Added new unit tests to verify Windows functionality
Continues work on #153
> feat: add Windows support for os shim

- crates/chat-cli/src/cli/chat/skim_integration.rs
- crates/fig_os_shim/src/fs.rs
- crates/fig_os_shim/src/process_info/pid.rs
- crates/fig_os_shim/src/process_info/windows.rs
Hello. I actively use the amazon-q-developer CLI and find the Agent Coding features very helpful. While trying out the recently added `/context add` fuzzy finder(skim) feature, I noticed one issue that could be improved, which led me to open this Pull Request.
When opening the fuzzy finder, I found that files and directories listed in `.gitignore` — such as `node_modules`, `dist`, and `build` — were still appearing in the file list. I believe that only valid files authored by developers should appear in the fuzzy finder’s list. Since files under `dist`, `node_modules`, `build` are typically generated or compiled artifacts rather than developer-authored source code, it would be helpful to exclude them from the fuzzy finder. Especially in the case of TypeScript, **the transpiled JavaScript …
> feat: integrate git-aware file selection in fuzzy finder

- Cargo.lock
- Cargo.toml
- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/cli/user.rs
- crates/fig_os_shim/src/fs.rs
- crates/fig_os_shim/src/process_info/pid.rs
- crates/fig_os_shim/src/process_info/windows.rs
- Copying over #1369 to the new `chat_cli` binary
- Setting `webpki-roots` to `0.26.8` since later versions have the license `CDLA-Permissive-2.0` which is prohibited.
- Run `cargo +nightly fmt`
> chore: copy infer license to new chat cli, rust cargo +nightly fmt

- crates/chat-cli/src/api_client/clients/streaming_client.rs
- crates/chat-cli/src/api_client/model.rs
- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/message.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/cli/chat/tools/tool_index.json
- crates/chat-cli/src/cli/chat/util/images.rs
- crates/chat-cli/src/cli/chat/util/mod.rs
- crates/chat-cli/src/platform/mod.rs
- crates/chat-cli/src/platform/os.rs
- crates/fig_api_client/src/clients/streaming_client.rs
- crates/fig_api_client/src/model.rs
> Support images with fs_read

- crates/chat-cli/src/cli/chat/mod.rs
#1334 
Displays a special UI when current context tokens exceed the limit
> fix(/usage): handles token overflow UI

- crates/chat-cli/src/auth/builder_id.rs
- crates/chat-cli/src/auth/secret_store/sqlite.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/parser.rs
- crates/chat-cli/src/cli/mod.rs
- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/platform/env.rs
- crates/chat-cli/src/platform/fs.rs
- crates/chat-cli/src/settings/sqlite.rs
- crates/chat-cli/src/util/directories.rs
- Updating tests so that `cargo test` passes
> chore: get cargo test to pass

- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/gh_issue.rs
- crates/chat-cli/src/cli/chat/util/mod.rs
#1254 
https://github.com/user-attachments/assets/83a688fd-cf55-46c6-b871-f979b4202366
> fix(/context): gracefully handle huge context files + ux

- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/tools/tool_index.json
- Adds a dummy tool in the tool schema
- Adds check in the conversation invariant check to replace failed tool calls with names that do not exist in the tool list
- Adds logic in get tools to include a retry message for the model to call tools by its full name
> fix: tool calls with incorrect name corrupts conversation

- crates/chat-cli/src/cli/chat/command.rs
- crates/chat-cli/src/cli/chat/mod.rs
* Fixed the uncleaned styling after tool call 
* Don't throw when a slash file path is provided at the beginning of the user input
> fix: images related issues

- crates/fig_os_shim/src/fs.rs
- crates/fig_proto/build.rs
- crates/fig_util/Cargo.toml
- crates/fig_util/src/directories.rs
- crates/fig_util/src/manifest.rs
- crates/fig_util/src/process_info/mod.rs
- crates/fig_util/src/process_info/windows.rs
- crates/fig_util/src/shell.rs
This PR continues the implementation of Windows support for the Amazon Q Developer CLI by adding and improving Windows-specific functionality across several core utility modules.
- Added Windows-specific implementation for downloading and setting up protoc
- Created separate functions for Windows and Unix platforms
- Implemented Windows-specific checksum verification and extraction using PowerShell
- Defined Windows directory paths following Windows conventions:
- Base directory: `%LOCALAPPDATA%\Fig`
- Resources: `%LOCALAPPDATA%\Fig\resources`
- Managed binaries: `%LOCALAPPDATA%\Fig\bin`
- Socket paths: `%LOCALAPPDATA%\Fig\sockets\figterm\$SESSION_ID.sock`
- Added Windows-specific implementations for runtime directories and file paths
- Updated tests to include Windows-specific path …
> feat: continue Windows implementation

- crates/chat-cli/src/api_client/model.rs
- crates/chat-cli/src/cli/chat/command.rs
- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/hooks.rs
- crates/chat-cli/src/cli/chat/message.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/cli/chat/util/mod.rs
- Implementing `/import` and `/export` builtin commands for importing and exporting conversation state to/from a JSON file.
- Derive `Serialize` and `Deserialize` for `ConversationState`
- Adding a wrapper around `aws_smithy_types::Document` that implements `Serialize` and `Deserialize`
- Fixing `/help` text spacing for `/usage`, and adding text for `/import` and `/export`
The goal here is to improve debuggability of the current chat session. There's more improvements to be made around saving request metadata and persistence options (e.g. including context files) but for now this is a good first pass.
> feat: add /import and /export commands

- crates/chat-cli/src/cli/chat/mod.rs
> fix: rotating tip coloring and ordering

- crates/q_cli/src/cli/mod.rs
Spawns task to ignore sigint in parent process when spawning chat. 
This is to fix when chat is invoked from q_cli (as opposed to a standalone bin), sigint will kill the parent process that spawns the chat, thus also killing chat (even though chat is properly handling the sigint). 
> fix: spawns task to ignore sigint in parent process when spawning chat

- crates/chat-cli/src/cli/chat/tools/thinking.rs
> chore: makes thinking opt-in by default

- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/hooks.rs
- crates/chat-cli/src/cli/chat/mod.rs
- Fixing issues around conversation state serialization. Now, context and stdout handles are appropriately rehydrated after deserializing a conversation.
We should really refactor `ConversationState` serialization into separate types so that this is cleaner, but the intention is to fix the immediate issues for now in time for bug bashing today.
> fix: bugs around serialization

- crates/chat-cli/src/cli/chat/mod.rs
> fix: display loading UI after tool execution

- crates/chat-cli/src/cli/chat/cli.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/mod.rs
Also deletes the past conversation history.
> feat(args): --new arg to bypass persistent conversations

- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/execute_bash.rs
This change aligns the purpose message with the command output and removes visual misalignment by rendering the purpose inline using a consistent arrow symbol.
**before**:
**now**:
> Fix: Make shell command purpose display more natural

- crates/q_cli/src/cli/mod.rs
- crates/q_cli/src/cli/user.rs
- crates/q_cli/src/util/mod.rs
> feat(auth): interactive login if logged out for `q` or `q chat`

- feed.json
- Updating the changelog with the latest commits.
> chore: update changelog

- crates/chat-cli/src/cli/chat/mcp.rs
CI `cargo test` fails with the error:
```
failures:
---- cli::chat::mcp::tests::ensure_file_created_and_loaded stdout ----
thread 'cli::chat::mcp::tests::ensure_file_created_and_loaded' panicked at crates/chat-cli/src/cli/chat/mcp.rs:362:14:
called `Result::unwrap()` on an `Err` value: EOF while parsing a value at line 1 column 0
Location:
crates/chat-cli/src/cli/chat/tool_manager.rs:211:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
cli::chat::mcp::tests::ensure_file_created_and_loaded
```
The current implementation saves and reads from files immediately which seems to cause flakiness when ran with other tests. Therefore, just ignoring it for now to help ensure stable builds.
By submitting this pull request, I confirm …
> fix: ignore flakey test in ci

- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/message.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/parser.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
> Persistant conv invariant

- build-scripts/build.py
- build-scripts/signing.py
- Adding `qchat` to the Linux minimal build.
> fix: qchat build on linux minimal

- feed.json
- Updating `/import` and `/export` to `/save` and `/load` in `feed.json`, since those are the correct command names.
> fix: /save and /load in feed.json

- crates/chat-cli/src/cli/chat/prompt.rs
- feed.json
- Changing the default edit mode back to `Emacs` since using `Vi` is causing some confusion with copy/paste and `ctrl+j` where the cursor is not at the end of the line.
- Adding `feed.json` entries for the `mcp` subcommand.
> fix: default chat edit mode to Emacs, feed.json mcp subcommand copy

- crates/chat-cli/src/aws_common/user_agent_override_interceptor.rs
- crates/chat-cli/src/database/mod.rs
- crates/fig_desktop_api/src/requests/profile.rs
- Adding the app version to the user agent.
- Fixing an issue where state cannot be deserialized from the desktop app. This only happens for the telemetry client id currently, but we need to ensure that any state shared across chat and the desktop app does not get desync'd.
Before and after of the user agent:
> fix: broken state for telemetryClientId, user agent versioning

- crates/chat-cli/src/mcp_client/client.rs
> fix: mcp client now ignores non json rpc bytes

- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- Tools and prompts are sorted by MCP server alphabetically. Built-in tools always come come first
- Within each category (MCP), they are sorted by name alphabetically.
- Slightly adjust /tools footer and fixes it so that the tip appears.
> feat(mcp): sort tools and prompts

- Cargo.lock
- crates/amzn-codewhisperer-client/Cargo.toml
- crates/amzn-codewhisperer-client/src/config.rs
- crates/amzn-codewhisperer-client/src/protocol_serde/shape_user_input_message.rs
- crates/amzn-codewhisperer-client/src/types/_user_input_message.rs
- Updating the `amzn-codewhisperer-client` to the latest version.
> chore: update amzn-codewhisperer-client

- crates/chat-cli/src/cli/chat/conversation_state.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/database/settings.rs
> feat: adds server load timeout for no interactive mode

- Cargo.lock
- crates/semantic_search_client/Cargo.toml
- crates/semantic_search_client/src/client/embedder_factory.rs
- crates/semantic_search_client/src/embedding/benchmark_test.rs
- crates/semantic_search_client/src/embedding/mod.rs
- crates/semantic_search_client/src/embedding/trait_def.rs
- crates/semantic_search_client/src/error.rs
Removing onnx runtime for now as it's causing problems cross platform, besides in order to get a reliable ans safe way to use the binding, they will require to be compiled and either use stating linking or dynamic linking. Dynamic linking is more problematic and could cause frustration on many users and in same way static linking is not trivial causing the release to be tricky as well.
As if we want to provide static linking fro this library will require major effort, I'm reverting it for now.
> fix: Removes onnx runtime

- .cargo/config.toml
- Cargo.lock
- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/lib.rs
- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/util/mod.rs
- crates/chat-cli/src/util/process/mod.rs
- crates/chat-cli/src/util/process/unix.rs
- crates/chat-cli/src/util/process/windows.rs
- crates/chat-cli/src/util/system_info/linux.rs
- crates/chat-cli/src/util/system_info/mod.rs
- crates/chat-cli/src/util/system_info/windows.rs
This PR enhances the Amazon Q CLI with cross-platform process termination capabilities and optimizes Windows performance through stack size adjustments. These improvements ensure consistent behavior across operating systems while addressing Windows-specific memory constraints.
• Added Windows-specific implementation for process termination
• Ensured consistent behavior between Windows, macOS, and Linux platforms
• Implemented proper error handling for process termination failures
• **Increased thread stack size allocation for Windows environments**
• Optimized memory management for Windows-specific constraints
• Implemented platform-specific code paths for process termination
• Used Windows API for Windows and POSIX signals for Unix-based systems
• Added proper error handling and logging …
> feat(windows): implement multi platform process kill

- crates/fig_desktop/README.md
- packages/dashboard-app/README.md
`N/A`
This PR fixed readme in dashboard app.
> fix: readme in dashboard app

- crates/chat-cli/src/cli/chat/command.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/server_messenger.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/mcp_client/messenger.rs
https://github.com/aws/amazon-q-developer-cli/issues/1856
The TLDR is that because tool list calls are now done passively, early errors with mcp server load is terminating the mcp server loading status task prematurely.
- Precompuates total number of servers (which are used to determine when to terminate the mcp loading status task) prior to spawning the task
- Changes display task to use async task as opposed to spawning a dedicated blocking thread. This was previously needed because we were holding onto a stdout lock. But we are no longer doing that, thus rendering the dedicated blocking thread unnecessary.
- Adds `/mcp` slash command to show server load records.
*Testing some workflows:*
- Everything should be loaded before …
> Fix mcp loading status

- crates/chat-cli/src/auth/builder_id.rs
- crates/fig_auth/src/builder_id.rs
> fix: add stalled stream protection config to SSO client

- build-config/buildspec-linux.yml
- build-config/buildspec-macos.yml
- build-scripts/qchatbuild.py
- build-scripts/qchatmain.py
- build-scripts/util.py
- crates/chat-cli/.gitignore
- crates/chat-cli/build.rs
- Adding the logic required for building (and signing) the `qchat` executable.
- Created a new build script, will have a follow-up PR to remove all of the dead code inside `build-scripts` and rename to `scripts`. This was done just to minimize the diff for this PR.
> feat: update build scripts to build qchat

- crates/chat-cli/src/cli/chat/message.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/cli/chat/tools/tool_index.json
- crates/q_cli/src/cli/mod.rs
Enhanced the `fs_read` tool to support batch operations, allowing multiple file/directory operations in a single command while maintaining backward compatibility.
**1. Core Structure Updates:**
- Modified `FsRead` struct to support batch operations via operations: `Option<Vec<FsReadOperation>>`
- Added optional `summary` field for better UX when describing batch operations
- Maintained backward compatibility for single operations
**2. Mixed Output Support**
- Added `OutputKind::Mixed { text: String, images: RichImageBlocks }` variant to handle operations that return both text and images
- Ensures all operation results (text and images) are properly passed to the model
- Fixed issue where batch operations with images would lose text …
> (feat): Add support for batch file reading in fs_read tool 

- crates/chat-cli/src/cli/agent.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
> Fix: error from merge for fs read

- crates/chat-cli/src/cli/agent.rs
When we launch from home directory, the migration workflow is no able to discern agent configs from local and global are the same set of config, thus erroneously warning users about conflicts that does not exist. 
> fixes migration workflow not differentiating between home dir and cwd

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/mod.rs
Fixes scenario where invalid agents are chosen, fallback does not correctly show active agent. 
Agents are assumed in the following order: 
1. The agent name specified by the start command via --agent (this is the agent_name that's
passed in)
2. If the above is missing or invalid, assume one that is specified by chat.defaultAgent
3. If the above is missing or invalid, assume the in-memory default
> fix(agent): agent fallback behavior

- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/database/settings.rs
Adding boolean setting for history hints. If the settings is not set, it's taken as false by default.
```
q settings chat.enableHistoryHints true
```
> feat: Adding boolean setting for history hints

- .github/workflows/terminal-bench.yaml
- terminal-bench-test/main.py
- terminal-bench-test/setup_amazon_q.sh
*Description of changes:* Adds a new yaml, bash script, and python file that allow terminal-bench to run on a GitHub runner through a manual trigger as a github action. These runs use arjbal AWS credentials for sigv4 + s3 bucket access.
> Terminal bench manual trigger github action

- crates/chat-cli/src/cli/chat/mod.rs
*Description of changes:* Compact history was failing if tool_use_results was too long and we had <= 2 messages in history. The bug fix was that we need to truncate the long message down to 25,000 length at most if we have very few items in history. Otherwise, it would constantly enter the branch for ChatError::CompactHistoryFailure. 
> Bug fix for /compact on large messages

- crates/chat-cli/src/cli/chat/prompt.rs
Improve code block detection in MultiLineValidator.
The previous implementation incorrectly treated a single ``` as both start and end marker. Now properly detects incomplete code blocks by counting backtick markers - an odd count indicates an incomplete block.
- Count occurrences of ``` in input
- Consider block incomplete if count is odd
- Maintain existing behavior for backslash continuation
> fix: improve code block detection in MultiLineValidator

- crates/chat-cli/src/cli/chat/cli/compact.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/parser.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/telemetry/core.rs
- crates/chat-cli/src/telemetry/definitions.rs
- crates/chat-cli/src/telemetry/mod.rs
- crates/chat-cli/telemetry_definitions.json
- Fixing an issue with `codewhispererterminal_customToolOutputTokenSize` metric not recording the correct size - MCP tools always return JSON, but we would only return the token size if the JSON is a string rather than any arbitrary value
- Adding `codewhispererterminal_recordUserTurnCompletion` as a new telemetry event. This records telemetry for a **user turn**. This is done by adding additional fields to `RequestMetadata` returned by the response stream parser, and updating `ChatSession::send_chat_telemetry` to use an additional parameter  `is_end_turn`, which will send this additional telemetry event for requests that we know will end the current turn.
- Adding `codewhispererterminal_mcpServerName` to the `codewhispererterminal_mcpServerInit` telemetry event. …
> feat: add user turn metrics, and more info in request metadata

- crates/chat-cli/src/cli/agent/legacy/mod.rs
- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/agent/root_command_args.rs
- crates/chat-cli/src/cli/chat/cli/profile.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/mcp.rs
- crates/chat-cli/src/telemetry/core.rs
- crates/chat-cli/src/telemetry/mod.rs
- crates/chat-cli/telemetry_definitions.json
- Adding telemetry for agent configuration initialization on `q chat` startup. See the `telemetry_definitions.json` file for the spec
- Adding telemetry for tool execution timing
- Fixing `codewhispererterminal_mcpServerInit` to include credential start url
> feat: add telemetry for agent config and tool execution timing

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/agent/root_command_args.rs
- crates/chat-cli/src/util/directories.rs
Local agents should be sourced from `.amazonq/agents` and not `.aws/amazonq/agents`.
As titled. 
> fix(agent): local agents being sourced from incorrect local path

- docs/SUMMARY.md
- Currently the docs link to built-in tools are broken, this fixes it.
> fix: broken link in docs to built-in tools

- crates/chat-cli/src/cli/chat/cli/tools.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
Changes hashing of tool origin to use struct discriminate for native namespace. Previously native tool namespace is hashed as "native".
This potentially collides with mcp server names (i.e. should user wish to use the name "native" for an mcp server").
> fix: uses struct discriminates as hash key for native tools

- crates/chat-cli/src/cli/chat/cli/usage.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/execute/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/util/mod.rs
This PR addresses a potential prompt injection issue by removing hidden/control Unicode characters from:
User input (e.g. chat prompt)
Tool outputs (e.g. `fs_read`, `execute_bash` responses)
Specifically, we strip characters in the following ranges:
```
U+E0000–U+E007F (Unicode TAG)
U+200B–U+200F, U+2028–U+202F, U+205F–U+206F, U+FFF0–U+FFFC, U+FFFF
```
These characters are rarely used in normal text but may be exploited to hide invisible instructions.
Unit tests are added to verify both detection and removal behavior.
> fix: Sanitize hidden Unicode characters from user and tool inputs

- crates/chat-cli/src/auth/builder_id.rs
- crates/chat-cli/src/cli/chat/cli/context.rs
- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/cli/model.rs
- crates/chat-cli/src/cli/chat/cli/usage.rs
- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/util/test.rs
- Adding new experimental models for internal Amazon users. This required some refactoring around the model selection logic for checking against the authentication state.
Examples of behavior when authenticated as a non-Amazon user are provided below.
Trying to launch with `--model`:
Trying to launch with `chat.defaultModel` set to one of the new models:
> feat: add experimental model for amazon users

- docs/agent-format.md
Using the Rust agent example in Q Dev CLI threw an error because the JSON contained invalid commas. Fixed and tested locally.
> Fix docs: Rust agent example JSON invalid

- Cargo.lock
- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/message.rs
- Previously the backend API would add a timestamp as part of the system prompt. Now, it is being removed in favor of letting the client implement this behavior.
- Only adding the timestamp for new user prompts, since tool use results don't have any content to be sent with the prompt.
- Reasoning behind having a timestamp: this enables temporal questions like "what did we do in the last hour" to be answered.
> feat: add timestamp for new user prompts

- Cargo.lock
- crates/chat-cli/src/cli/chat/cli/knowledge.rs
- crates/chat-cli/src/cli/chat/tools/knowledge.rs
- crates/chat-cli/src/database/settings.rs
- crates/chat-cli/src/util/directories.rs
- crates/chat-cli/src/util/knowledge_store.rs
- crates/semantic-search-client/Cargo.toml
- crates/semantic-search-client/README.md
- crates/semantic-search-client/src/client/async_implementation.rs
- crates/semantic-search-client/src/client/implementation.rs
- crates/semantic-search-client/src/config.rs
- crates/semantic-search-client/src/embedding/trait_def.rs
- crates/semantic-search-client/src/lib.rs
- crates/semantic-search-client/src/pattern_filter.rs
- crates/semantic-search-client/src/processing/file_processor.rs
- crates/semantic-search-client/src/processing/mod.rs
- crates/semantic-search-client/src/processing/text_chunker.rs
- crates/semantic-search-client/src/types.rs
- docs/knowledge-management.md
• **CLI Integration**: Added --include and --exclude flags to /knowledge add command
• **Pattern Filter Module**: New pattern_filter.rs with comprehensive glob-style pattern matching
• **Async File Processing**: Enhanced file_processor.rs with async pattern filtering capabilities
• **Rename from contexts from knowledge bases**: Changed the semantic on how we refer to the knowledge entries.
• **"Are you sure?" : Changed confirmation message
• **Increased amount of extensions supported*: Added more text extensions to list of supported files.
• **Automatic migration and new path for knowledge bases**: Now they will live in ./aws/amazonq/knowledge_bases
• **Settings Schema**: Added new settings for KnowledgeChunkSize, KnowledgeChunkOverlap, KnowledgeMaxFiles, KnowledgeDefaultIncludePatterns, …
> Knowledge beta improvements

- crates/chat-cli/src/cli/chat/cli/model.rs
- crates/chat-cli/src/cli/chat/mod.rs
The service side has changed the model name from` claude-4-sonnet` to `claude-sonnet-4`. Add a client-side mapping to ensure backward compatibility when invoking Q or updating q settings for chat.defaultModel with either model. This should also remain consistent with the plugin.
> fix:  Add client-side modelName mapping for backward compatibility 

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/execute/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/tools/fs_write.rs
- crates/chat-cli/src/cli/chat/tools/use_aws.rs
- docs/agent-format.md
Premise
Currently in the agent config we require a tool to be included in “allowedTools” in order for its corresponding entry in “toolsSettings” to take effect. 
Feedback 1
If the toolsSettings is permission related, this would result in a stricter permission for the tool than if it were to have no toolsSettings at all. From users feedback, the consensus is that this is unintuitive. 
For example, config A is looser than config B:
```json
// Config A
{
"allowedTools": [
"fs_read",
"execute_bash",
"fs_write"
],
"toolsSettings": {}
}
```
```json
// Config B
{
"allowedTools": [
"fs_read",
"execute_bash",
"fs_write"
],
"toolsSettings": {
"execute_bash": {
"allowedCommands": ["git status"] // now only git status is permitted
}
}
}
```
Feedback 2
Having an entry for a …
> fix(agent): tool permission override

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tools/execute/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/tools/fs_write.rs
- crates/chat-cli/src/cli/chat/tools/use_aws.rs
- docs/agent-format.md
Reverts aws/amazon-q-developer-cli#2606
There are some issues with this commit: 
- execute isn't respecting allowed commands
- paths aren't being canonicalized prior to being turned into glob set (for fs_read and fs_write) 
- the anchors around denied commands / paths needs some more thoughts
> Revert "fix(agent): tool permission override"

- crates/chat-cli/src/cli/chat/parser.rs
- crates/chat-cli/src/cli/chat/tools/use_aws.rs
- docs/agent-format.md
- docs/built-in-tools.md
- The `use_aws` tool will print that the default profile is being used when missing, when in reality we do not fall back to using the default profile.
- Minor docs update
- Minor test update to add an assertion
> fix: use_aws printing default profile when its not used, minor updates to agent docs

- .github/workflows/release-notification.yaml
We need a Github Action to post notifications to slack. 
Added the required Github Actions file to achieve this. 
> feat: add github action for release notification

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/tools/custom_tool.rs
- crates/chat-cli/src/cli/chat/tools/knowledge.rs
- crates/chat-cli/src/util/pattern_matching.rs
fixed the ci failure introduced by https://github.com/aws/amazon-q-developer-cli/pull/2612
run `cargo +nightly fmt ` to fix the ci
> fix(ci): resolve CI pipeline failures

- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/cli/tangent.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/cli/chat/prompt_parser.rs
- crates/chat-cli/src/database/settings.rs
- crates/chat-cli/src/telemetry/core.rs
add tangent mode for isolated conversations
- Add /tangent command to toggle between normal and tangent modes
- Preserve conversation history during tangent for context
- Restore main conversation when exiting tangent mode
- Add Ctrl+T keyboard shortcut for quick access
- Visual indicator: green [T] prompt in tangent mode
- Comprehensive tests for state management and UI components
Allows users to explore side topics without polluting main conversation context.
> feat: add tangent mode for isolated conversations

- crates/chat-cli/src/telemetry/mod.rs
Short-Term fix for Validation errors -
// chatAddMessageEvent.timeBetweenChunks' : Member must have length less than or equal to 100
> Short-Term fix for SendTelemetry API Validation errors

- crates/chat-cli/src/cli/chat/cli/experiment.rs
- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/cli/chat/tools/introspect.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- docs/experiments.md
- Add new /experiment command
- Toggle selection interface with colored On/Off status indicators
- Include experiment descriptions and disclaimer about experimental features
> feat: add /experiment slash command for toggling experimental features

- crates/chat-cli/src/cli/chat/cli/experiment.rs
- docs/experiments.md
- Adding tangent mode to `/experiment` since it follows the same experimental paradigm as knowledge and thinking
> chore: add /tangent to /experiment

- docs/built-in-tools.md
added the documentation for introspect in the built in tools.
> docs: added the documentation for introspect in the built in tools.

- crates/chat-cli/src/cli/chat/line_tracker.rs
- crates/chat-cli/src/cli/chat/tools/fs_write.rs
Improves the accuracy of line contribution tracking by implementing proper diff-based calculation instead of using simple before/after line counts.
• **Enhanced FileLineTracker struct**: Added lines_added_by_agent and lines_removed_by_agent fields to track actual line changes
• **Improved lines_by_agent() method**: Now returns the sum of added and removed lines instead of absolute difference between before/after counts
• **Added calculate_diff_lines() method**: Analyzes different file operations (create, str_replace, insert, append) to accurately count line changes
The previous implementation used (after_lines - before_lines).abs() which could be inaccurate for operations that both add and remove lines. The new approach:
1. Create operations: Counts all lines in the new file as added
2. …
> Fix calculation for num-lines contributed by q-cli

- docs/knowledge-management.md
- Changed from ~/.q/knowledge_bases/ to ~/.aws/amazonq/knowledge_bases/
- Added _<alphanumeric-code> suffix to agent directory names
- Matches actual implementation behavior
> Update knowledge base directory path to reflect actual location

- crates/chat-cli/src/api_client/mod.rs
This change ensures we no longer send a `profileArn` when the CLI is pointed at a non-prod endpoint (e.g., alpha/gamma). Sending prod `profileArn` to preprod causes validation errors, so we now only attach it when the endpoint is the default prod one. It will default to IAD region if no profile is sending
This is mainly to unblock team testing on non-prod environments and make it easier for everyone to validate flows without hitting profile-related errors.
> chore: Skip sending profileArn when using custom endpoints

- docs/agent-format.md
- docs/knowledge-management.md
> feat: updating doc to surface /agent generate and note block for /knowledge

- crates/chat-cli/src/util/directories.rs
Today if a path has a trailing slash, the glob pattern will look like "/path-to-folder//**" (note the double slash). Glob doesn't work with double slash actually (it doesn't match anything). As a result, the permission management for fs_read and fs_write is broken when allowed or denied path has trailing slash.
The fix is to just manually remove the trailing slash.
Unit test
Integration test:
1. Create an agent like this
```
{
"$schema": "https://raw.githubusercontent.com/aws/amazon-q-developer-cli/refs/heads/main/schemas/agent-v1.json",
"name": "test-write",
"description": "test write permission", …
```
> Properly handle path with trailing slash in file matching

- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/tools/fs_read.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- crates/chat-cli/src/os/env.rs
Reduce default fs_read trust permission to current working directory only
Previously by default fs_read is trusted to read any file on user's file
system. This PR reduces the fs_read permission to CWD only. This means user
can still access any file under CWD without prompt. But if user needs to
access file outside CWD, she will be prompted for explicit approval.
User can still explicitly add fs_read to trusted tools in chat / agent
definition so fs_read can read any file without prompt.
This change essentially adds a layer of defense against prompt injection
by following the least-privilege principle.
1. launching Q CLI for CWD
```
~/Documents/Work/2025/Project/amazon-q-developer-cli $ cargo run --bin chat_cli
Compiling chat_cli v1.15.0 …
```
> Reduce default fs_read trust permission to current working directory only

- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/mcp_client/oauth_util.rs
Previously, credentials associated to mcp is only persisted on drop (i.e. when users switch agent or exit session). 
This PR changes it so that it is persisted as soon as it is obtained. 
There are two callsites where this happens: 
- Initial auth
- Token refresh 
> fix(mcp): remote mcp creds not being written when obtained

- crates/chat-cli/src/cli/chat/cli/tools.rs
As titled. This is needed to make it more obvious to users that actions need to be taken to authenticate. 
The real solution would be a bit more involved. This is here to bridge the gap until that lands. 
> chore(mcp): adds temp message to still loading section of /tools

- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/database/settings.rs
The reason is ctrl-f is the standard shortcut in UNIX for moving cursor forward by 1 character. You can find it being supported everywhere... in your browser, your terminal, etc.
Manually tested ctrl-g and ctrl-f in the CLI
Also tested overriding the shortcut through config:
```
~/Documents/Work/2025/Project/amazon-q-developer-cli/crates/chat-cli $ cargo run --bin chat_cli -- settings chat.autocompletionKey o
Compiling chat_cli v1.15.0 (/Users/moerben/Documents/Work/2025/Project/amazon-q-developer-cli/crates/chat-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 11.86s
Running …
```
> Change autocomplete shortcut from ctrl-f to ctrl-g

- crates/chat-cli/src/cli/agent/hook.rs
- crates/chat-cli/src/cli/agent/legacy/hooks.rs
- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/cli/hooks.rs
- crates/chat-cli/src/cli/chat/context.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/chat/tools/custom_tool.rs
- crates/chat-cli/src/cli/chat/tools/introspect.rs
- crates/chat-cli/src/cli/chat/tools/mod.rs
- docs/agent-format.md
- docs/hooks.md
feat: Add hook support for preToolUse and postToolUse
With this change, customer can define arbitrary command to be run
before and after tool use. Example definition:
```
"hooks": {
"preToolUse": [
{
"matcher": "execute_bash",
"command": "cat >> /tmp/bash_audit_log && echo >> /tmp/bash_audit_log"
}
],
"postToolUse": [
{
"matcher": "fs_write",
"command": "cargo fmt --all"
}
]
}
```
Hook command receives input from STDIN in JSON format. Hook command is run as a
separate process. It can return exit code and write to stdout / stderr.
Overall life cycle of a tool call:
system-level tool validation -> preToolUse -> user prompt for approving tool -> running tool -> postToolUse
Hook input
- hook_event_name
- cwd
- tool_name
- tool_input
- tool_response
Hook output handling
preToolUse
- Exit code …
> Support preToolUse and postToolUse hook

- crates/chat-cli/src/cli/chat/cli/clear.rs
Reset tool_uses, pending_tool_index, and tool_turn_start_time to prevent orphaned tool approval prompts after conversation history is cleared.
*Issue #, if available:* #2782
https://github.com/aws/amazon-q-developer-cli/issues/2782
> fix(chat): reset pending tool state when clearing conversation

- crates/chat-cli/src/cli/chat/tools/custom_tool.rs
As titled. 
This was added by mistake. The absent of this restrictions ensures config that are superset to our schema are still accepted. 
> fix: removes deny unknown fields in mcp config

- crates/chat-cli/src/cli/chat/cli/clear.rs
- crates/chat-cli/src/util/directories.rs
*Issue #, if available:* Credit to yayami3@ and erbenmo@ for identifying and providing initial fix in these PRs - 
1. https://github.com/aws/amazon-q-developer-cli/pull/2820
2. https://github.com/aws/amazon-q-developer-cli/pull/2926
*Description of changes:* This PR builds on top of - https://github.com/aws/amazon-q-developer-cli/pull/2820
1. Performs normalization even when the path starts with `/`. This addresses expansion in the case of path like `/absolute/./../path`
> Normalize and expand relative-paths to absolute paths

- crates/chat-cli/src/cli/agent/mod.rs
*Description of changes:* https://github.com/aws/amazon-q-developer-cli/pull/2846 set default auto-allow-readonly to false, but we still print the default message as readonly allowed for execute bash, which is confusing.
This PR updates the default message
> Update default tool label for execute bash

- crates/chat-cli/src/cli/chat/cli/editor.rs
- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/cli/prompts.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/util/directories.rs
resolve #2794 
This PR implements a comprehensive prompt management system that supports both global and local prompts. Users can now create, edit, and manage reusable prompt templates that are stored locally in their projects or globally across all projects.
*Features added*
1. **Global and Local Prompt Support**
- Global prompts: Stored in ~/.aws/amazonq/prompts/ (shared across all projects)
- Local prompts: Stored in <project>/.amazonq/prompts/ (project-specific)
- Priority system: Local prompts override global prompts when names conflict
2. **New Commands**
- `/prompts create <name>` - Create a new local prompt (`--content <content>` argument is also supported)
- `/prompts edit <name>` - Edit an existing prompt with automatic editor …
> feat(chat): expand support for /prompts command

- crates/chat-cli/src/cli/chat/cli/experiment.rs
- crates/chat-cli/src/cli/chat/cli/usage.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/cli/chat/prompt_parser.rs
- crates/chat-cli/src/database/settings.rs
Add experimental feature to show context window usage as a percentage in the chat prompt (e.g., "[rust-agent] 6% >"). The percentage is color-coded: green (<50%), yellow (50-89%), red (90-100%).
The feature is disabled by default and can be enabled via /experiment.
> feat: add context usage percentage indicator to prompt

- crates/chat-cli/src/cli/chat/cli/prompts.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
*Issue #, if available:* #2789
This PR improves the MCP prompts feature, focusing on better user experience and discoverability:
- **Details command**: Added `/prompts details` to show comprehensive prompt information including metadata and argument details
- **Enhanced list view**: Improved `/prompts list` with three-column layout showing descriptions and better formatting
- **Content preview**: Display fetched prompt content before AI processing to eliminate user confusion
- **Better error handling**: Replace raw JSON MCP server errors with user-friendly, actionable messages
- **Usage guidance**: Generate helpful usage examples from PromptBundle data for invalid parameter errors
- **Visual formatting**: Consistent terminal styling and proper content display for …
> feat(prompts): Enhanced MCP prompt management with improved UX

- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/cli/reply.rs
- crates/chat-cli/src/cli/chat/prompt.rs
I'm not sure if there is better process for this, but this is a small feature I've been wanting! In addition to `/editor`, you can now do `/reply`. It begins the editor with the assistant's last comments, quoted with `>`. I find this very useful particularly when Claude has given me a list of clarifications and I want to answer all of them.
*Concerns:*
I couldn't find any existing infra to unit-test this with. I was thinking that it'd be nice to have a way to "mock out" the editor, but that doesn't seem to be a thing. Maybe I missed it?
> Proposal: Add a `/reply` command

- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- The back-end limit on the maximum support conversation length has been removed, so we are instead relying on the current context window overflow logic to be used for managing conversation context length.
> chore: remove max limit on conversation length

- Cargo.lock
- Cargo.toml
- crates/chat-cli/src/cli/chat/checkpoint.rs
- crates/chat-cli/src/cli/chat/cli/checkpoint.rs
- crates/chat-cli/src/cli/chat/cli/experiment.rs
- crates/chat-cli/src/cli/chat/cli/hooks.rs
- crates/chat-cli/src/cli/chat/cli/mod.rs
- crates/chat-cli/src/cli/chat/cli/prompts.rs
- crates/chat-cli/src/cli/chat/cli/reply.rs
- crates/chat-cli/src/cli/chat/consts.rs
- crates/chat-cli/src/cli/chat/conversation.rs
- crates/chat-cli/src/cli/chat/mod.rs
- crates/chat-cli/src/cli/chat/prompt.rs
- crates/chat-cli/src/cli/chat/tool_manager.rs
- crates/chat-cli/src/cli/feed.json
- crates/chat-cli/src/mcp_client/client.rs
- crates/chat-cli/src/mcp_client/oauth_util.rs
Merges latest changes from main to prod for release 1.17.0
> Merge main with prod

- Cargo.lock
- Cargo.toml
- crates/chat-cli/Cargo.toml
- crates/chat-cli/src/cli/agent/mod.rs
- crates/chat-cli/src/cli/chat/context.rs
- Add the steering files path to default agent config resources
- Only include the steering files if it has front matter as always, or not having/having invalid front matter (always is the default)
> add support for always inclusion steering files

- crates/chat-cli/src/cli/chat/cli/knowledge.rs
- crates/chat-cli/src/cli/chat/tools/knowledge.rs
- docs/knowledge-management.md
- Unifies /knowledge status and /knowledge show
- Adds --path and --name args for consistency
- Add short flags: -n for --name, -p for --path
- Update documentation to reflect show/status unification and new flags
Usage examples:
/knowledge add -n myproject -p /path/to/project
/knowledge add --name docs --path /path/to/docs
/knowledge show  # Now shows both entries and operations
Simplified UX.
> feat: Unify show and status commands for knowledge

- crates/chat-cli/src/cli/chat/checkpoint.rs
- crates/chat-cli/src/cli/chat/mod.rs
- Add -f flag to git tag to allow overwriting existing tags
- Move turn checkpoints to end of list when updating to maintain correct chronological ordering
- Update turn checkpoint after each tool use to point to latest state
- Fix expand functionality to show correct tool checkpoints for each turn
> Fix multiple turn-checkpoints issue
