aws/amazon-q-developer-cli

Cargo.lock
=> chore(cargo): run `cargo update`

.github/dependabot.yml
=> ci: Update dependabot to not limit PR count

crates/fig_integrations/src/vscode/mod.rs, crates/fig_util/src/terminal.rs
vscode integrations add windsurf support
=> feat: VSCodeVariant add windsurf

typos.toml
=> chore: ignore more folders in typos

crates/fig_integrations/src/file.rs
=> fix: flaky fig_integration test

Cargo.lock, crates/fig_proto/Cargo.toml
=> Bump prost to 0.14

.github/workflows/rust.yml
=> ci: add code coverage tracking

.github/ISSUE_TEMPLATE/1_bug_report_template.yml, crates/fig_util/src/consts.rs, crates/q_cli/src/cli/issue.rs
=> feat: Add issue template and update `q issue` to point to this repo

.github/dependabot.yml, Cargo.lock
=> chore: Use Conventional Conventional for dependabot updates

.github/workflows/rust.yml, deny.toml
=> ci: run cargo deny

.github/workflows/typescript.yml, package.json, packages/api-bindings/src/auth.ts, packages/api-bindings/src/event.ts, packages/api-bindings/src/global.d.ts, packages/api-bindings/src/history.ts, packages/api-bindings/src/install.ts, packages/api-bindings/src/notifications.ts, packages/api-bindings/src/requests.ts, packages/api-bindings/src/utils.ts, packages/autocomplete-parser/src/constants.ts, packages/autocomplete-parser/src/loadHelpers.ts, packages/autocomplete-parser/src/loadSpec.ts, packages/autocomplete-parser/src/parseArguments.ts, packages/autocomplete-parser/tests/parseArguments.test.ts, packages/autocomplete/src/components/Suggestion.tsx, packages/autocomplete/src/components/SuggestionIcon.tsx, packages/autocomplete/src/fig/themes.ts, packages/autocomplete/src/generators/templateSuggestionsGenerator.ts, packages/autocomplete/src/history/index.ts, packages/autocomplete/src/hooks/keypress.ts, packages/autocomplete/src/state/generators.ts, packages/autocomplete/src/suggestions/sorting.ts, packages/eslint-config/src/common.ts, packages/shared/src/utils.ts, packages/shell-parser/src/command.ts, packages/shell-parser/src/parser.ts, pnpm-lock.yaml, vitest.config.ts
=> fix: add vite coverage and resolve various lints

crates/amzn-codewhisperer-client/src/config.rs, crates/amzn-codewhisperer-streaming-client/src/config.rs, crates/amzn-consolas-client/src/config.rs, crates/amzn-qdeveloper-client/src/config.rs, crates/amzn-qdeveloper-streaming-client/src/config.rs, crates/amzn-toolkit-telemetry/src/config.rs
=> chore: fix docs tests with invalid codeblock

packages/autocomplete/package.json, packages/dashboard/package.json
=> build: use `@amzn` namespace for private packages

Cargo.lock, Cargo.toml, feed.json
- Bumping the version to 1.5.1
- Adding feed.json updates
=> Bump version to 1.5.1

crates/fig_util/src/terminal.rs
- Adding support for Guake for #177 
=> feat: add guake terminal support

package.json, packages/api-bindings-wrappers/package.json, packages/api-bindings/package.json, packages/autocomplete-parser/package.json, packages/autocomplete/package.json, packages/dashboard/package.json, packages/eslint-config/package.json, packages/fuzzysort/package.json, packages/shared/package.json, packages/shell-parser/package.json, packages/tsconfig/package.json, packages/types/package.json, proto/package.json
=> chore: add repository to npm package.json

crates/fig_desktop/src/install.rs
=> test: add lock to flaky appimage install tests

crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/terminal.rs
=> fix: clean up chat changes

crates/fig_api_client/src/clients/streaming_client.rs, crates/fig_api_client/src/error.rs, crates/fig_api_client/src/model.rs, crates/q_cli/src/cli/chat/api.rs
=> feat: add history to ConversationState in StreamingClient::send_message

turbo.json
kinda subjective but tui is a lot better for viewing logs for each task
=> chore: enable tui in turborepo

Cargo.lock, Cargo.toml, feed.json
=> chore: bump version to 1.6.0

crates/fig_integrations/src/vscode/mod.rs, crates/fig_util/src/terminal.rs
[Positron](https://positron.posit.co/) is an IDE for data science based on VS Code.
=> feat: add support for Positron terminal

crates/fig_install/src/linux.rs, crates/fig_test_utils/src/lib.rs, crates/fig_test_utils/src/server.rs
- Addressing a comment in the previous pr adding fig_test_utils - #410 
- Adding doc comments/tests
=> refactor: Clean up fig_test_utils

build-scripts/build.py
=> fix: build script

Cargo.lock, Cargo.toml, feed.json
=>  chore: bump version to 1.6.1 

crates/fig_integrations/src/vscode/mod.rs, crates/fig_util/src/terminal.rs
=> feat: support for Trae

crates/figterm/src/main.rs
=> feat: add Q_AUTOCOMPLETE_DISABLED env var

crates/fig_aws_common/src/user_agent_override_interceptor.rs
=> fix: add app version to user agent

crates/fig_api_client/src/clients/shared.rs, crates/figterm/src/inline/mod.rs
=> fix: flush telemetry events more often and rate limit

Cargo.lock, Cargo.toml, feed.json
=> chore: bump to 1.6.2

crates/figterm/src/inline/mod.rs
=> fix: remove unwrap in inline

Cargo.lock, Cargo.toml, feed.json
=> chore: bump to 1.6.3

crates/amzn-codewhisperer-client/src/config.rs, crates/amzn-codewhisperer-streaming-client/src/config.rs, crates/amzn-consolas-client/src/config.rs, crates/amzn-qdeveloper-client/src/config.rs, crates/amzn-qdeveloper-streaming-client/src/config.rs, crates/amzn-toolkit-telemetry/src/config.rs, crates/fig_api_client/src/endpoints.rs, crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/tools/execute_bash.rs, crates/q_cli/src/cli/chat/tools/fs_read.rs, crates/q_cli/src/cli/chat/tools/fs_write.rs, crates/q_cli/src/cli/chat/tools/use_aws.rs, crates/q_cli/tests/chat_response_stubs/fs_read.json, crates/q_cli/tests/chat_response_stubs/use_aws.json
- Use fig settings instead of state for the chat API override
- Minor UX improvements
=> fix: display, use settings instead of state for api endpoint

crates/q_cli/src/cli/chat/mod.rs
=> Updates spinner message

Cargo.lock, crates/q_cli/Cargo.toml, crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/tools/fs_write.rs, crates/q_cli/src/cli/chat/tools/mod.rs, crates/q_cli/tests/chat_response_stubs/fs_write.json, crates/q_cli/tests/chat_response_stubs/fs_write_long_file.json, deny.toml
- add syntax highlighting using `syntect`
=> feat: syntax highlighting for fs_write

crates/q_cli/src/cli/chat/mod.rs
=> fix: updates welcome message to also include programming capabilities

crates/q_cli/src/cli/chat/tools/tool_index.json
=> fix: enhances description of aws tools to make it more robust

crates/q_cli/src/cli/chat/tools/fs_read.rs, crates/q_cli/src/cli/chat/tools/fs_write.rs, crates/q_cli/src/cli/chat/tools/mod.rs, crates/q_cli/tests/chat_response_stubs/fs_read.json
- Printing the read file contents during `fs_read` invocation
=> feat: print read file contents

crates/q_cli/src/cli/chat/tools/fs_write.rs, crates/q_cli/src/cli/chat/tools/mod.rs
- Adding line numbers to nonstylized output
=> feat: add line numbers to nonstylized text

crates/q_cli/src/cli/chat/tools/mod.rs, crates/q_cli/src/cli/chat/tools/use_aws.rs
=> fix: fix aws tool description format

crates/q_cli/src/cli/chat/tools/mod.rs, crates/q_cli/src/cli/chat/tools/tool_index.json, crates/q_cli/src/cli/chat/tools/use_aws.rs
- Updating the `use_aws` tool spec to conform more closely to the CLI version.
=> fix: Improve the use_aws tool specification

crates/q_cli/src/cli/chat/mod.rs
=> feat: shows initial user message as prompt

crates/q_cli/src/cli/chat/tools/fs_write.rs
=> fix: provides better error message

crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/parser.rs
- Add a waiting animation for tool uses.
=> feat: add waiting animation for tool uses

crates/fig_api_client/src/clients/streaming_client.rs, crates/fig_api_client/src/error.rs, crates/q_cli/src/cli/chat/error.rs, crates/q_cli/src/cli/chat/mod.rs
=> feat: show users when quota is breached

crates/q_cli/src/cli/chat/conversation_state.rs, crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/parser.rs
- Update `q chat` telemetry events to handle new chat messages, and correct tool use event details.
- Generating a random conversation id on every `q chat`, and a random message id on every assistant response.
- Removed the `ConversationId` stream event. This is required since the backend is stateless and doesn't provide conversation id's or message id's.
- Removing the `Message` wrapper in conversation_state since it's unnecessary.
- Other minor random cleanup.
=> fix: telemetry events in q chat, other refactoring and cleanup

crates/q_cli/src/cli/chat/conversation_state.rs
- Always adding tool results in cases where the last assistant message contains tool uses, and the current set next message does not contain tool results.
=> fix: tool results missing in certain edge cases

crates/q_cli/src/cli/chat/mod.rs
**vscode**:
**macos default terminal**:
**ghostty**:
=> fix: removes emoji from welcome msg

crates/q_cli/src/cli/chat/mod.rs
- Adding fake messages in the history when the user sigint's during tool execution. This ensures the state is reset appropriately.
=> fix: sigint during tool execution

crates/q_cli/src/cli/chat/conversation_state.rs, crates/q_cli/src/cli/chat/mod.rs
- Printing tool descriptions when consent is not required.
=> fix: show command descriptions for auto-invoke tools

crates/q_cli/src/cli/chat/tools/git.rs, crates/q_cli/src/cli/chat/tools/mod.rs, crates/q_cli/src/cli/chat/tools/tool_index.json
=> feat: adds git tool

crates/q_cli/src/cli/chat/tools/tool_index.json, crates/q_cli/src/cli/chat/tools/use_aws.rs
=> fix: standalone argument for use aws

crates/q_cli/src/cli/chat/mod.rs
=> feat: adds accept all toggle in welcome msg

Cargo.lock, Cargo.toml, crates/fig_api_client/src/clients/streaming_client.rs, feed.json
=> chore: bump version to 1.7.0

Cargo.lock, deny.toml
- adding `paste` to deny.toml ignore
=> chore: add paste to cargo deny ignore

package.json, pnpm-lock.yaml
=> chore: run pnpm update

crates/fig_integrations/src/vscode/mod.rs, crates/fig_util/src/terminal.rs
Add support for windsurf next.
=> feat: add windsurf-next support

crates/q_cli/src/cli/chat/mod.rs
- Fixes a small bug where executing a command (e.g. `/acceptall`) after a tool use response would deny that tool use.
- Added a `skip_printing_tools` parameter to the `ChatState::PromptUser` state to prevent long tools from overshadowing the command output.
=> fix: stop running commands from disabling tool uses

crates/q_cli/src/cli/chat/input_source.rs
- Add support for multi-line input. This is done by just checking if the last character in the input is a backslash `\`, and if so, continue appending to the current input buffer.
=> feat: add support for multiline input, for lines ending with a backslash

crates/q_cli/src/cli/chat/input_source.rs
- Removing the backslash in multi-line input.
=> fix: remove backslash in multi-line input

bundle/linux/install.sh
Enhanced the glibc version detection with multiple fallback methods:
- Added dedicated function to check if glibc version is sufficient
- Implemented three detection methods (direct library check, ldd, getconf)
- Added support for ARM64 architecture by checking additional library paths
- Made error messages more informative with dynamic version requirements
- Fixed parameter passing to allow setup command to receive arguments
These changes improve reliability of installation across different Linux distributions and architectures.
=> 🔧 Improve glibc version detection in install.sh

Cargo.lock, Cargo.toml, feed.json
- Bumping the version to 1.7.2
=> bskiser/bump version 1.7.2

README.md
#949 
Recommending contributors to add `codebase-summary.md` to Q context for faster onboarding experience and to increase `/context` usage.
=> docs: add onboarding tips for using Q CLI in README

crates/q_cli/src/cli/chat/mod.rs
#817 
Reworded the assistant response message for more clarity.
Will need a follow up PR to root-cause.
=> fix(chat): update timeout message for clarity in assistant responses

README.md
=> docs(README): add local development instructions for q chat

crates/q_cli/src/cli/mod.rs
=> Repositions `q` as the main entry point

README.md
=> docs(README): add testing and formatting instructions for Q CLI crate

crates/q_cli/src/cli/chat/mod.rs
#1071 
https://github.com/user-attachments/assets/e702d6a6-5c23-473f-8f95-d58e5a835d77
=> fix(chat ux): exit thinking state using ctrl + c

crates/q_cli/src/cli/chat/context.rs
=> fix(context): unify path validation by merging global and profile paths

crates/q_cli/src/cli/installation.rs, crates/q_cli/src/cli/mod.rs, crates/q_cli/src/cli/user.rs
#1082 
Add query params to `q login` cmd with pro license.
=> feat(login): add query params to q login cmd with pro license

Cargo.lock, crates/q_cli/src/cli/chat/command.rs, crates/q_cli/src/cli/chat/context.rs, crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/util/mod.rs, crates/q_cli/src/util/token_counter.rs
* Reworded things to make it less confusing about what `/context` is for. 
* Users are adding "rules", not really "files" to the context. That had been made clear in this PR.
* Added token count est for each file
=> feat(chat ui): improve /context ui

crates/q_cli/src/cli/chat/command.rs, crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/prompt.rs
https://github.com/user-attachments/assets/5c26ef82-fcea-43b0-9301-b02ff32f8bd1
=> feat(chat /context): add `--expand` flag to print out file content

crates/q_cli/src/cli/chat/mod.rs
- Adding an error log statement to help debug cases where users are reporting seeing the "Response timed out" message that should only be kept in the history rather than ever displayed to the user.
=> fix(chat): add error log if we receive a response timeout message

crates/q_cli/src/cli/chat/command.rs, crates/q_cli/src/cli/chat/mod.rs
https://github.com/user-attachments/assets/0436c9ef-8058-4cd1-bcf7-c88ce6c71bdc
=> fix(/context): handle filepaths with white spaces

crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/tools/mod.rs
=> fix(/tools reset): add existence check before resetting tool permissions

crates/q_cli/src/cli/chat/mod.rs, crates/q_cli/src/cli/chat/tools/mod.rs
=> feat(/tools ux): improve UI and refactor codes

crates/q_cli/src/cli/chat/mod.rs
https://github.com/user-attachments/assets/68196242-af70-43b8-9ce7-e219ad185f3b
For narrow screens, we show a lite version:
=> feat(chat ui): brand new greeting UI + rotating tips

crates/q_cli/src/cli/chat/context.rs, crates/q_cli/src/cli/chat/mod.rs
=> fix(context): deduplicate context files

README.md
We should try our best to minimize the number of steps users have to go through to get started.
This will make it a one-click download, potentially increase our conversion
=> doc(README): increase conversion using direct download link

crates/q_cli/src/cli/chat/context.rs, crates/q_cli/src/cli/chat/conversation_state.rs, crates/q_cli/src/cli/chat/hooks.rs
=> test(context): add /context hooks tests for HookExecutor, ContextManager

crates/q_chat/src/lib.rs
- Don't retry compacting the history if it fails due to context window overflow. This should resolve a scenario where compaction fails and gets auto-retried, ultimately resulting in an infinite loop of failures.
=> fix: don't retry compaction if it fails

Cargo.lock, Cargo.toml, feed.json
- Bumping the version to 1.8.1
=> chore: bump version to 1.8.1

crates/q_chat/src/context.rs, crates/q_chat/src/skim_integration.rs
*Description of changes:* This allows the user to use the fuzzy selection to set, delete, or rename profiles
https://github.com/user-attachments/assets/9c8eb7e4-3985-4640-b014-30916ca39efd
=> feat: fuzzy select profiles

crates/q_chat/src/tools/gh_issue.rs
=> fix: gh issue transcript size exceeding url limit

crates/q_chat/src/tools/fs_read.rs
https://amzn-aws.slack.com/archives/C08H70N155F/p1745872374219259
=> Pretty print fs_read

crates/q_chat/src/tools/execute_bash.rs
=> makes it so that chained command always requires permission

crates/q_chat/src/lib.rs
=> copy changes for mcp release

Cargo.lock, Cargo.toml, feed.json
- Bumping the version to 1.9.0 and adding feed.json changes
=> chore: bump version to 1.9.0

crates/fig_api_client/src/clients/client.rs, crates/fig_api_client/src/clients/streaming_client.rs, crates/q_cli/src/cli/user.rs
- Fix the CLI login flow to allow changing the start url
- Set the profile arn correctly
=> fix: add correct profile arn for clients, allow changing start url from cli login

crates/q_chat/src/tools/use_aws.rs
The AWS CLI allows you to add information to the user agent string by setting the AWS_EXECUTION_ENV env var. This string then shows up in CloudTrail logs to enable users to audit their Q CLI usage.
This PR adds a string like "AmazonQ-For-CLI Version/0.0.0" to the user agent of AWS CLI commands executed by the use_aws tool. This is the same string as used in [crates/fig_aws_common/src/user_agent_override_interceptor.rs](https://github.com/aws/amazon-q-developer-cli/blob/f0b5a0a3263c0f901d5c685f74117d2c84dff8f4/crates/fig_aws_common/src/user_agent_override_interceptor.rs) for requests to the Q Dev backend.
=> fix: use_aws tool adds app name to the AWS CLI user agent string

crates/q_chat/src/lib.rs
=> shorten terminal notification tip

crates/q_chat/src/tools/custom_tool.rs
https://github.com/aws/amazon-q-developer-cli/issues/1465
Currently tools is a treated as a must have for an mcp server. If an mcp server is to have no tools, the server will fail to load. 
This does not align with the protocol. This is to fix that. 
Note that the logic flow affected in this PR will be reworked following the resolution of https://github.com/aws/amazon-q-developer-cli/issues/1466.
=> fix: makes tool optional in a mcp server

crates/q_chat/src/tool_manager.rs
https://github.com/aws/amazon-q-developer-cli/issues/1468
Here we surface the invariant of empty tool description as an error. 
=> fix: adds empty description check for tool schema

crates/amzn-codewhisperer-client/src/config.rs, crates/amzn-codewhisperer-streaming-client/src/config.rs, crates/amzn-consolas-client/src/config.rs, crates/amzn-qdeveloper-streaming-client/src/config.rs, crates/amzn-toolkit-telemetry/src/config.rs
- Fixing `cargo test` failures
=> fix: broken doc tests in generated clients

crates/fig_desktop/README.md
`N/A`
this PR fixed path to the dashboard README. (really small change..)
=> chore: fix path to the dashboard README

crates/chat-cli/Cargo.toml, crates/chat-cli/src/lib.rs, crates/chat-cli/src/mcp_client/client.rs, crates/chat-cli/src/mcp_client/mod.rs, crates/chat-cli/test_mcp_server/test_server.rs
=> fix: test for mcp client after move

crates/chat-cli/src/telemetry/util.rs
- Ignoring a broken test in CI to unblock builds
=> fix: ignore broken test

crates/chat-cli/src/cli/chat/tool_manager.rs
=> adds new line after mcp loading status

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/user.rs, crates/chat-cli/src/database/mod.rs, crates/chat-cli/src/util/consts.rs, crates/fig_settings/src/sqlite/mod.rs, crates/q_cli/src/cli/mod.rs, feed.json
=> fix: migrations logic to appropriately handle all migrations

crates/chat-cli/src/database/mod.rs, crates/fig_settings/src/sqlite/mod.rs
=> chore: fix tests

crates/chat-cli/src/cli/chat/tools/fs_read.rs
=> fix: remove unnecessary print

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/chat/cli/compact.rs, crates/chat-cli/src/cli/chat/conversation.rs, crates/chat-cli/src/cli/chat/message.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/chat/util/mod.rs, crates/chat-cli/src/cli/feed.json, crates/chat-cli/src/database/settings.rs
- Copying over the changes from: https://github.com/aws/amazon-q-developer-cli-autocomplete/pull/407
- Bumping the version to v1.12.4
=> fix: issues with /compact, bumping the version to v1.12.4

crates/chat-cli/src/cli/chat/mod.rs
Updated the error message for `ModelOverloadedError` to provide appropriate guidance based on whether the CLI is running in interactive or non-interactive mode and not show the backtrace information to users. 
Interactive mode:
Non-interactive mode:
=> fix: revise model unavailable msg in both interactive and non-interactive mode

crates/chat-cli/src/cli/chat/cli/model.rs
=> chore: remove claude-3.5-sonnet model from options due to potential deprecation

CONTRIBUTING.md, README.md, book.toml, docs/SUMMARY.md, docs/agent.md, docs/draft/the-agent-format-2.md, docs/introduction.md, docs/native-tools.md, docs/the-agent-format.md
=> feat: add agent documentation

crates/chat-cli/src/cli/chat/cli/context.rs, crates/chat-cli/src/cli/chat/cli/hooks.rs, crates/chat-cli/src/cli/chat/cli/knowledge.rs, crates/chat-cli/src/cli/chat/cli/mod.rs, crates/chat-cli/src/cli/chat/cli/profile.rs, crates/chat-cli/src/cli/chat/cli/prompts.rs, crates/chat-cli/src/cli/chat/cli/tools.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/telemetry/core.rs, crates/chat-cli/src/telemetry/mod.rs, crates/chat-cli/telemetry_definitions.json
=> chore: Add telemetry event for slash command execution

crates/chat-cli/src/auth/builder_id.rs, crates/chat-cli/src/cli/chat/cli/compact.rs, crates/chat-cli/src/cli/chat/cli/editor.rs, crates/chat-cli/src/cli/chat/prompt.rs
- Adding extra debug auth checks
- Fixing /editor and /compact argument parsing
- Not including multi-line prompts in the chat hinting
- Fixing broken build
=> chore: apply misc fixes and changes from the autocomplete repo

crates/chat-cli/src/cli/agent/mod.rs, crates/chat-cli/src/cli/agent/root_command_args.rs, crates/chat-cli/src/cli/chat/cli/hooks.rs, crates/chat-cli/src/cli/chat/cli/profile.rs, crates/chat-cli/src/cli/chat/context.rs, crates/chat-cli/src/cli/mod.rs, crates/chat-cli/src/util/directories.rs
As titled. 
Also included in this PR are fixes to some existing tests broken by recent merges. 
=> feat(agent): root and slash subcommand for agent list, create, and rename

crates/chat-cli/src/cli/agent/mcp_config.rs, crates/chat-cli/src/cli/mcp.rs
=> fix(agent): mcp command producing malformed mcp.json

crates/chat-cli/src/cli/agent/mod.rs, docs/the-agent-format.md
=> fix(agent): in memory default not reading from legacy mcp json

crates/chat-cli/src/cli/chat/cli/model.rs, crates/chat-cli/src/cli/chat/mod.rs
- Copying the changes over from https://github.com/aws/amazon-q-developer-cli-autocomplete/pull/451
=> feat: Prompt users to select a different model when at capacity

crates/chat-cli/src/cli/chat/conversation.rs
=> feat(agent): includes agent prompt into context message

docs/introduction.md
Changed the description so it no longer makes it sound like this is the main or only facet of the docs.
=> clarifying doc into

crates/chat-cli/src/cli/chat/tools/execute/mod.rs
Cherry picking commit from https://github.com/aws/amazon-q-developer-cli-autocomplete/pull/444 to the chat repo. 
Had to change it slightly since the structure of the function has changed with the inclusion of agent. 
- https://github.com/aws/amazon-q-developer-cli-autocomplete/pull/444
- Resolve merge conflict
=> fix: execute bash perms for potential unwanted execution

crates/chat-cli/src/cli/chat/cli/profile.rs
Slash command created agents do not show up in `/agent list` afterwards.
As titled. 
=> fix(agent) slash command created agent not showing up post creation

Cargo.lock, Cargo.toml
- bumping the version to 1.13.0
=> chore: bump version to 1.13.0

docs/agent-format.md
=> chore(agent): removes disabled field on mcp server from the docs

crates/chat-cli/src/cli/chat/cli/context.rs
=> fix(agent): cleans up mentions of profile in slash commands

crates/chat-cli/src/cli/agent/mod.rs, crates/chat-cli/src/cli/agent/root_command_args.rs, crates/chat-cli/src/cli/chat/cli/profile.rs, docs/agent-format.md
- Adds root and slash command to set user defined default
- Makes name field non-optional
- Makes version field non-optional
=> feat(agent): adds root and slash command to set user defined default

crates/chat-cli/src/cli/chat/skim_integration.rs
=> fix(agent): removes mentioning of profile

schemas/agent-v1.json
=> fix: update agent-v1.json to include schema

Cargo.lock, Cargo.toml
- Bumping the version to 1.13.1
=> chore: bump version to 1.13.1

Cargo.lock, Cargo.toml
=> chore: bump version to 1.13.2

crates/chat-cli/src/cli/chat/mod.rs
Fixes #2371
Updated link to one that works. Assume this is the one that should be targeted by the CLI help docs.
=> docs: Update link for MCP in Q developer CLI help output.

crates/chat-cli/src/cli/chat/cli/model.rs, crates/chat-cli/src/cli/chat/tools/knowledge.rs
- Removing gpt-oss model since it is not yet ready, and we need to release v1.13.2.
=> chore: remove gpt-oss model

crates/chat-cli/src/cli/chat/tools/knowledge.rs, docs/agent-format.md
=> fix: updates doc for prompt

crates/chat-cli/src/cli/chat/conversation.rs, crates/chat-cli/src/cli/chat/line_tracker.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/chat/tools/fs_write.rs, crates/chat-cli/src/cli/chat/tools/mod.rs, crates/chat-cli/src/telemetry/core.rs, crates/chat-cli/src/telemetry/mod.rs, crates/chat-cli/telemetry_definitions.json
=> adding in agent contribution metric

crates/chat-cli/src/api_client/mod.rs, crates/chat-cli/src/api_client/retry_classifier.rs
This PR implements the first phase of the Q CLI unified retry strategy, introducing intelligent retry handling with adaptive rate limiting to improve user experience during service overload 
conditions. The implementation leverages AWS Smithy's adaptive retry strategy combined with custom error classification to provide seamless error handling.
• **Changed from**: Standard retry mode with single attempt (max_attempts = 1)
• **Changed to**: Adaptive retry mode with client-retry backoff (max_attempts = 3, max_backoff = 10s)
• **Benefits**: Enables client-side rate limiting and automatic throttling detection
• **New file**: crates/chat-cli/src/api_client/retry_classifier.rs
• **Purpose**: Handles Q CLI-specific error patterns and service throttling conditions
• **Key features**:
• **Monthly …
=> Implement Retry Classifier for Adaptive Rate Limiting

Cargo.lock, Cargo.toml
=> chore: bump version to 1.13.3

Cargo.lock, Cargo.toml
=> chore: bump version to 1.14.0

crates/chat-cli/src/cli/chat/tool_manager.rs, crates/chat-cli/src/telemetry/core.rs, crates/chat-cli/src/telemetry/mod.rs, crates/chat-cli/telemetry_definitions.json
=> adding telemetry for mcp tool names available and mcp tool names selected

crates/chat-cli/src/cli/chat/cli/mod.rs, crates/chat-cli/src/cli/chat/cli/tangent.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/chat/tools/introspect.rs, crates/chat-cli/src/database/settings.rs
Added feature gating of tangent mode for both introspect and tangent mode.
=> feat: added feature gating of tangent mode

crates/chat-cli/src/cli/agent/mod.rs, crates/chat-cli/src/cli/chat/conversation.rs, crates/chat-cli/src/cli/chat/tools/introspect.rs, crates/chat-cli/src/cli/chat/tools/tool_index.json
=> fix: added summary to tangent and showed correct label for introspect

crates/chat-cli/src/cli/chat/cli/profile.rs, crates/chat-cli/src/cli/chat/mod.rs
- **fixing bugs**
- **formatting**
=> this contains bug fix from the bug bash for agent generate

crates/chat-cli/src/api_client/delay_interceptor.rs, crates/chat-cli/src/api_client/mod.rs
Update retry-interceptor warning message
=> Update retry-interceptor warning message

crates/chat-cli/src/cli/chat/tools/introspect.rs, docs/introspect-tool.md, docs/tangent-mode.md
We need to provide more documentation about the new features so that introspect is able to answer better about it.
=> feat: added tangent & introspect docs & provided to introspect

crates/chat-cli/src/cli/chat/cli/clear.rs, crates/chat-cli/src/cli/chat/conversation.rs
=> fix: Dont preserve summary when conversation is cleared

crates/chat-cli/src/mcp_client/client.rs
=> fix(mcp): stale / non-refreshable creds not being deleted

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/feed.json
=> chore: version bump

crates/chat-cli/src/cli/chat/tools/fs_read.rs
as titled
Updated format command to use `cargo +nightly fmt`
=> fix: CI format check by enforcing nightly cargo fmt

crates/chat-cli/src/mcp_client/client.rs
=> fix(mcp): command not being expanded for stdio

Cargo.lock, Cargo.toml
*Description of changes:* Bump up version for hotfix
=> Bump up version for hotfix

crates/chat-cli/src/mcp_client/oauth_util.rs
=> chore: copy change for warning message for oauth redirect page

crates/chat-cli/src/mcp_client/client.rs
=> changes how mcp command gets expanded

crates/chat-cli/src/cli/agent/mod.rs, crates/chat-cli/src/cli/chat/cli/prompts.rs
=> [fomat] Runs Clippy and cargo +nightly fmt

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/feed.json, docs/experiments.md
* Bump version
* Adds feed
* Updates experiments
=> Release092625

crates/chat-cli/src/cli/feed.json
=> [docs] Updates feed to reflect latest change

crates/chat-cli/src/cli/chat/cli/prompts.rs, crates/chat-cli/src/cli/chat/cli/reply.rs, crates/chat-cli/src/cli/chat/tool_manager.rs
=> fix: tests for rmcp type changes

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/feed.json
Updated feed to reflect latest changes
=> [chore] Updates feed for 09/29 Release

Cargo.lock, Cargo.toml, crates/chat-cli/src/cli/chat/cli/model.rs, crates/chat-cli/src/cli/chat/context.rs, crates/chat-cli/src/cli/feed.json
=> chore: sync prod with main

crates/chat-cli/src/cli/chat/cli/checkpoint.rs, crates/chat-cli/src/cli/chat/cli/experiment.rs, crates/chat-cli/src/cli/chat/cli/knowledge.rs, crates/chat-cli/src/cli/chat/cli/tangent.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/chat/prompt.rs, crates/chat-cli/src/cli/chat/skim_integration.rs, crates/chat-cli/src/cli/chat/tools/introspect.rs, crates/chat-cli/src/cli/chat/tools/knowledge.rs, crates/chat-cli/src/cli/chat/tools/thinking.rs, crates/chat-cli/src/cli/chat/tools/todo.rs, crates/chat-cli/src/cli/experiment/experiment_manager.rs, crates/chat-cli/src/cli/experiment/mod.rs, crates/chat-cli/src/cli/mod.rs
* Creates Experiment Manager
* Creates a master toggle to disable experiments.
* Replaces usage of settings in favor of ExperimentManager
=> feat: Adds experiment manager

crates/chat-cli/src/cli/agent/legacy/mod.rs
=> fix: Typos error

crates/chat-cli/src/cli/chat/cli/logdump.rs
=> fid: Fixes clippy

crates/chat-cli/src/auth/consts.rs, crates/chat-cli/src/cli/chat/cli/context.rs, crates/chat-cli/src/cli/chat/cli/hooks.rs, crates/chat-cli/src/cli/chat/cli/mod.rs, crates/chat-cli/src/cli/chat/cli/tools.rs, crates/chat-cli/src/cli/chat/mod.rs, crates/chat-cli/src/cli/chat/tools/delegate.rs, crates/chat-cli/src/cli/user.rs, crates/chat-cli/src/constants.rs, crates/chat-cli/src/lib.rs, crates/chat-cli/src/main.rs, crates/chat-cli/src/util/consts.rs, crates/chat-cli/src/util/ui.rs
move user facing messages to constants
=> chore: move messages to constants
